// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa_API.Data;

#nullable disable

namespace Villa_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230508135347_AddVillaTableWithBogus")]
    partial class AddVillaTableWithBogus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SqureFeet")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Hic debitis ullam rerum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(6600),
                            Details = "Et aut nesciunt iure voluptates earum ipsam dolor nam laudantium.",
                            ImageURL = "https://picsum.photos/640/480/?image=144",
                            Name = "Marcus Stiedemann II",
                            Occupancy = 1,
                            Rate = 4.0,
                            SqureFeet = 742,
                            UpdatedDate = new DateTime(2022, 8, 10, 2, 54, 51, 422, DateTimeKind.Local).AddTicks(3085)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Mollitia nihil molestiae placeat dicta aut ratione odit deleniti.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(6800),
                            Details = "Voluptas id harum saepe.",
                            ImageURL = "https://picsum.photos/640/480/?image=817",
                            Name = "Miss Sidney Buckridge",
                            Occupancy = 4,
                            Rate = 1.0,
                            SqureFeet = 753,
                            UpdatedDate = new DateTime(2023, 4, 24, 13, 58, 26, 606, DateTimeKind.Local).AddTicks(3704)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Voluptatum optio quam dignissimos rerum aut maiores quibusdam quos aut.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(6890),
                            Details = "Omnis quo atque maxime et magnam.",
                            ImageURL = "https://picsum.photos/640/480/?image=862",
                            Name = "Miss Brendan Corkery",
                            Occupancy = 1,
                            Rate = 1.0,
                            SqureFeet = 182,
                            UpdatedDate = new DateTime(2022, 7, 31, 0, 31, 12, 760, DateTimeKind.Local).AddTicks(4979)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Excepturi praesentium placeat ut.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(6980),
                            Details = "Porro voluptatem aut possimus voluptate et sed pariatur quia officia.",
                            ImageURL = "https://picsum.photos/640/480/?image=487",
                            Name = "Willis Cassin II",
                            Occupancy = 1,
                            Rate = 1.0,
                            SqureFeet = 850,
                            UpdatedDate = new DateTime(2022, 5, 17, 1, 6, 57, 627, DateTimeKind.Local).AddTicks(9911)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Explicabo tempora sed.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7060),
                            Details = "Culpa sed vel repellendus officiis et accusantium qui id.",
                            ImageURL = "https://picsum.photos/640/480/?image=847",
                            Name = "Terrence Rutherford IV",
                            Occupancy = 6,
                            Rate = 4.0,
                            SqureFeet = 347,
                            UpdatedDate = new DateTime(2022, 11, 20, 20, 52, 31, 443, DateTimeKind.Local).AddTicks(6448)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Quae omnis autem perspiciatis soluta autem voluptatem saepe fugit.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7140),
                            Details = "Nemo eos unde tempora minus.",
                            ImageURL = "https://picsum.photos/640/480/?image=456",
                            Name = "Edward Legros Jr.",
                            Occupancy = 2,
                            Rate = 2.0,
                            SqureFeet = 591,
                            UpdatedDate = new DateTime(2023, 3, 9, 9, 28, 43, 45, DateTimeKind.Local).AddTicks(3478)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Sint molestiae et veritatis quisquam accusamus.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7220),
                            Details = "Et voluptas vitae itaque et facilis aliquam minima doloremque doloribus.",
                            ImageURL = "https://picsum.photos/640/480/?image=50",
                            Name = "Mrs. Beulah Nolan",
                            Occupancy = 3,
                            Rate = 5.0,
                            SqureFeet = 590,
                            UpdatedDate = new DateTime(2023, 2, 6, 11, 26, 9, 716, DateTimeKind.Local).AddTicks(3148)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Neque debitis officia nulla voluptate vero nihil corporis eos.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7300),
                            Details = "Modi ea est accusantium consectetur harum eveniet et ipsam.",
                            ImageURL = "https://picsum.photos/640/480/?image=920",
                            Name = "Doug Wyman V",
                            Occupancy = 9,
                            Rate = 4.0,
                            SqureFeet = 791,
                            UpdatedDate = new DateTime(2023, 3, 20, 8, 30, 54, 21, DateTimeKind.Local).AddTicks(1970)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Optio impedit beatae.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7370),
                            Details = "Iure nostrum sint hic et repellat distinctio id eaque.",
                            ImageURL = "https://picsum.photos/640/480/?image=1029",
                            Name = "Bruce Beahan V",
                            Occupancy = 9,
                            Rate = 4.0,
                            SqureFeet = 882,
                            UpdatedDate = new DateTime(2023, 2, 20, 14, 43, 31, 402, DateTimeKind.Local).AddTicks(9434)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Et quae optio adipisci modi voluptatem placeat.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7460),
                            Details = "Saepe quis eos et accusamus sapiente velit voluptate.",
                            ImageURL = "https://picsum.photos/640/480/?image=925",
                            Name = "Ms. Manuel Armstrong",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 886,
                            UpdatedDate = new DateTime(2023, 1, 16, 17, 12, 41, 587, DateTimeKind.Local).AddTicks(9582)
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "Saepe quos aut voluptate in blanditiis et ut.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7530),
                            Details = "Ut dicta facilis.",
                            ImageURL = "https://picsum.photos/640/480/?image=430",
                            Name = "Dr. Louis Cummings",
                            Occupancy = 7,
                            Rate = 1.0,
                            SqureFeet = 384,
                            UpdatedDate = new DateTime(2023, 4, 11, 11, 6, 40, 788, DateTimeKind.Local).AddTicks(8439)
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "Molestiae illum ab possimus officiis atque porro ducimus voluptatum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7610),
                            Details = "Sed a ea excepturi omnis ipsam voluptatem eum.",
                            ImageURL = "https://picsum.photos/640/480/?image=796",
                            Name = "Mrs. Roosevelt Botsford",
                            Occupancy = 10,
                            Rate = 5.0,
                            SqureFeet = 504,
                            UpdatedDate = new DateTime(2022, 7, 21, 9, 57, 57, 190, DateTimeKind.Local).AddTicks(8377)
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "Occaecati est dolorem soluta nam maiores eligendi natus quia id.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7700),
                            Details = "Sit repudiandae esse qui magnam possimus quia iusto ipsa.",
                            ImageURL = "https://picsum.photos/640/480/?image=1063",
                            Name = "Sherry Hagenes II",
                            Occupancy = 7,
                            Rate = 2.0,
                            SqureFeet = 321,
                            UpdatedDate = new DateTime(2022, 6, 23, 12, 2, 2, 374, DateTimeKind.Local).AddTicks(5173)
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "Laboriosam recusandae cumque sit vel eum non quis provident.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7770),
                            Details = "Fugiat nobis facere dolores autem.",
                            ImageURL = "https://picsum.photos/640/480/?image=872",
                            Name = "Cary Shanahan DVM",
                            Occupancy = 2,
                            Rate = 1.0,
                            SqureFeet = 471,
                            UpdatedDate = new DateTime(2023, 5, 3, 13, 10, 12, 182, DateTimeKind.Local).AddTicks(3019)
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "Tempora est itaque tenetur id sed id autem fuga.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7830),
                            Details = "Qui quia dolores.",
                            ImageURL = "https://picsum.photos/640/480/?image=340",
                            Name = "Georgia Klein I",
                            Occupancy = 7,
                            Rate = 3.0,
                            SqureFeet = 471,
                            UpdatedDate = new DateTime(2022, 7, 29, 15, 2, 20, 552, DateTimeKind.Local).AddTicks(9031)
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "Pariatur dolorum qui quis porro.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(7920),
                            Details = "Veniam nisi numquam praesentium necessitatibus rerum consequatur.",
                            ImageURL = "https://picsum.photos/640/480/?image=874",
                            Name = "Mr. Vernon Hilll",
                            Occupancy = 7,
                            Rate = 5.0,
                            SqureFeet = 177,
                            UpdatedDate = new DateTime(2022, 8, 10, 0, 1, 23, 854, DateTimeKind.Local).AddTicks(3440)
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "Porro quis quia et mollitia velit quia ullam sint.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8000),
                            Details = "Eveniet molestias quas ea sapiente et deserunt ex.",
                            ImageURL = "https://picsum.photos/640/480/?image=830",
                            Name = "Ms. Francis Goodwin",
                            Occupancy = 3,
                            Rate = 2.0,
                            SqureFeet = 573,
                            UpdatedDate = new DateTime(2022, 9, 10, 15, 12, 17, 620, DateTimeKind.Local).AddTicks(7277)
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "Nam quasi minima natus quaerat quam.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8070),
                            Details = "Qui maxime id occaecati perferendis deleniti fugit et ut.",
                            ImageURL = "https://picsum.photos/640/480/?image=392",
                            Name = "Alice Reinger II",
                            Occupancy = 8,
                            Rate = 4.0,
                            SqureFeet = 120,
                            UpdatedDate = new DateTime(2022, 5, 18, 20, 25, 14, 345, DateTimeKind.Local).AddTicks(1413)
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "Adipisci fugiat a aliquid laudantium expedita ipsam quisquam.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8130),
                            Details = "Tenetur ea distinctio.",
                            ImageURL = "https://picsum.photos/640/480/?image=556",
                            Name = "Mr. Susan Fisher",
                            Occupancy = 2,
                            Rate = 4.0,
                            SqureFeet = 516,
                            UpdatedDate = new DateTime(2022, 8, 8, 12, 59, 26, 855, DateTimeKind.Local).AddTicks(3329)
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "Ut inventore iure in.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8180),
                            Details = "Quis laudantium cumque.",
                            ImageURL = "https://picsum.photos/640/480/?image=857",
                            Name = "Emily Kertzmann MD",
                            Occupancy = 9,
                            Rate = 4.0,
                            SqureFeet = 997,
                            UpdatedDate = new DateTime(2022, 6, 8, 14, 30, 38, 608, DateTimeKind.Local).AddTicks(6626)
                        },
                        new
                        {
                            Id = 21,
                            Amenity = "Et vel repellat velit.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8240),
                            Details = "Accusantium et optio accusantium magni.",
                            ImageURL = "https://picsum.photos/640/480/?image=790",
                            Name = "Lucia Reichert PhD",
                            Occupancy = 9,
                            Rate = 5.0,
                            SqureFeet = 878,
                            UpdatedDate = new DateTime(2023, 3, 25, 16, 29, 52, 832, DateTimeKind.Local).AddTicks(7736)
                        },
                        new
                        {
                            Id = 22,
                            Amenity = "Autem suscipit repellat autem expedita quo sit asperiores quos porro.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8310),
                            Details = "Et in quod voluptas nesciunt.",
                            ImageURL = "https://picsum.photos/640/480/?image=232",
                            Name = "Irving Champlin Sr.",
                            Occupancy = 7,
                            Rate = 5.0,
                            SqureFeet = 70,
                            UpdatedDate = new DateTime(2022, 10, 8, 0, 1, 7, 838, DateTimeKind.Local).AddTicks(5185)
                        },
                        new
                        {
                            Id = 23,
                            Amenity = "Corporis placeat ducimus et commodi eligendi.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8390),
                            Details = "Suscipit veniam magni amet et explicabo quia sunt.",
                            ImageURL = "https://picsum.photos/640/480/?image=218",
                            Name = "Mr. Doug Mann",
                            Occupancy = 8,
                            Rate = 2.0,
                            SqureFeet = 462,
                            UpdatedDate = new DateTime(2022, 6, 27, 21, 50, 53, 833, DateTimeKind.Local).AddTicks(2873)
                        },
                        new
                        {
                            Id = 24,
                            Amenity = "Modi illo dolor voluptatem velit in.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8450),
                            Details = "Sit praesentium dolorem.",
                            ImageURL = "https://picsum.photos/640/480/?image=501",
                            Name = "Jose Steuber MD",
                            Occupancy = 2,
                            Rate = 3.0,
                            SqureFeet = 613,
                            UpdatedDate = new DateTime(2022, 7, 24, 0, 9, 7, 79, DateTimeKind.Local).AddTicks(7079)
                        },
                        new
                        {
                            Id = 25,
                            Amenity = "Cupiditate architecto enim tenetur voluptas quae dolor rerum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8520),
                            Details = "Et molestias dignissimos quia dolorum ut quia culpa.",
                            ImageURL = "https://picsum.photos/640/480/?image=799",
                            Name = "Mae Rath III",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 940,
                            UpdatedDate = new DateTime(2022, 10, 24, 9, 5, 47, 64, DateTimeKind.Local).AddTicks(1421)
                        },
                        new
                        {
                            Id = 26,
                            Amenity = "Autem qui qui dicta aliquam libero.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8590),
                            Details = "Eveniet a et voluptatum asperiores iusto modi.",
                            ImageURL = "https://picsum.photos/640/480/?image=931",
                            Name = "Miss Mindy Sanford",
                            Occupancy = 9,
                            Rate = 5.0,
                            SqureFeet = 141,
                            UpdatedDate = new DateTime(2022, 11, 4, 17, 57, 4, 841, DateTimeKind.Local).AddTicks(872)
                        },
                        new
                        {
                            Id = 27,
                            Amenity = "Velit mollitia eligendi.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8650),
                            Details = "Dolorem velit eum laudantium repellendus quia dolorem sunt.",
                            ImageURL = "https://picsum.photos/640/480/?image=579",
                            Name = "Miss Angel Effertz",
                            Occupancy = 10,
                            Rate = 5.0,
                            SqureFeet = 215,
                            UpdatedDate = new DateTime(2022, 7, 25, 0, 55, 32, 57, DateTimeKind.Local).AddTicks(9302)
                        },
                        new
                        {
                            Id = 28,
                            Amenity = "Repellendus sint vel excepturi similique nihil id ut iste eum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8720),
                            Details = "In qui nihil eum accusamus animi et facere.",
                            ImageURL = "https://picsum.photos/640/480/?image=582",
                            Name = "Mrs. Inez Rosenbaum",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 265,
                            UpdatedDate = new DateTime(2022, 8, 30, 15, 58, 8, 92, DateTimeKind.Local).AddTicks(8730)
                        },
                        new
                        {
                            Id = 29,
                            Amenity = "Quaerat iste aspernatur eos deserunt officiis nemo.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8810),
                            Details = "Quaerat id earum quibusdam voluptatum aliquam.",
                            ImageURL = "https://picsum.photos/640/480/?image=443",
                            Name = "Mr. Iris Walker",
                            Occupancy = 8,
                            Rate = 2.0,
                            SqureFeet = 820,
                            UpdatedDate = new DateTime(2022, 7, 16, 16, 33, 3, 432, DateTimeKind.Local).AddTicks(1218)
                        },
                        new
                        {
                            Id = 30,
                            Amenity = "Nesciunt veniam qui perspiciatis et sint voluptate sequi.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8880),
                            Details = "Minus atque doloremque occaecati provident nemo velit voluptate.",
                            ImageURL = "https://picsum.photos/640/480/?image=631",
                            Name = "Miss Diane Dietrich",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 453,
                            UpdatedDate = new DateTime(2022, 6, 21, 1, 34, 20, 833, DateTimeKind.Local).AddTicks(9303)
                        },
                        new
                        {
                            Id = 31,
                            Amenity = "Consequatur reprehenderit dolor.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(8940),
                            Details = "Quia debitis harum earum reprehenderit delectus accusantium quod.",
                            ImageURL = "https://picsum.photos/640/480/?image=1070",
                            Name = "Dr. Christian Stokes",
                            Occupancy = 8,
                            Rate = 1.0,
                            SqureFeet = 771,
                            UpdatedDate = new DateTime(2023, 2, 28, 9, 40, 22, 773, DateTimeKind.Local).AddTicks(9761)
                        },
                        new
                        {
                            Id = 32,
                            Amenity = "Similique recusandae reiciendis neque aperiam aut ut voluptas.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9010),
                            Details = "Et velit nemo autem consequatur incidunt hic veritatis.",
                            ImageURL = "https://picsum.photos/640/480/?image=285",
                            Name = "Dr. William Osinski",
                            Occupancy = 8,
                            Rate = 5.0,
                            SqureFeet = 870,
                            UpdatedDate = new DateTime(2022, 8, 26, 1, 15, 9, 368, DateTimeKind.Local).AddTicks(5346)
                        },
                        new
                        {
                            Id = 33,
                            Amenity = "Voluptate fugit provident neque maiores porro aut a.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9080),
                            Details = "Maiores ut consectetur sint minima officiis qui eius.",
                            ImageURL = "https://picsum.photos/640/480/?image=561",
                            Name = "Diane Sanford DDS",
                            Occupancy = 6,
                            Rate = 5.0,
                            SqureFeet = 269,
                            UpdatedDate = new DateTime(2023, 1, 13, 22, 59, 4, 37, DateTimeKind.Local).AddTicks(2974)
                        },
                        new
                        {
                            Id = 34,
                            Amenity = "Quae dicta ipsam eum reiciendis corrupti molestiae quos.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9150),
                            Details = "Impedit est perspiciatis id eum perspiciatis odit nihil voluptatem reiciendis.",
                            ImageURL = "https://picsum.photos/640/480/?image=543",
                            Name = "Bridget Raynor IV",
                            Occupancy = 10,
                            Rate = 1.0,
                            SqureFeet = 585,
                            UpdatedDate = new DateTime(2022, 6, 17, 11, 58, 3, 774, DateTimeKind.Local).AddTicks(5870)
                        },
                        new
                        {
                            Id = 35,
                            Amenity = "Iste occaecati eum alias quia omnis eaque tempore.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9240),
                            Details = "Deleniti voluptatem alias reprehenderit.",
                            ImageURL = "https://picsum.photos/640/480/?image=827",
                            Name = "Andres Muller Jr.",
                            Occupancy = 2,
                            Rate = 2.0,
                            SqureFeet = 453,
                            UpdatedDate = new DateTime(2022, 8, 14, 6, 50, 39, 730, DateTimeKind.Local).AddTicks(2284)
                        },
                        new
                        {
                            Id = 36,
                            Amenity = "Omnis ducimus placeat modi voluptatibus assumenda quibusdam cupiditate ut consequatur.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9320),
                            Details = "Consequuntur ratione quibusdam officiis fuga quia qui perferendis eos fugiat.",
                            ImageURL = "https://picsum.photos/640/480/?image=715",
                            Name = "Rodney Reichel Jr.",
                            Occupancy = 3,
                            Rate = 5.0,
                            SqureFeet = 781,
                            UpdatedDate = new DateTime(2022, 5, 25, 3, 8, 2, 766, DateTimeKind.Local).AddTicks(2111)
                        },
                        new
                        {
                            Id = 37,
                            Amenity = "Dolorum at eligendi quia.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9380),
                            Details = "Consequatur ratione a aspernatur minima et blanditiis sit.",
                            ImageURL = "https://picsum.photos/640/480/?image=932",
                            Name = "Mr. Bill Ortiz",
                            Occupancy = 6,
                            Rate = 5.0,
                            SqureFeet = 282,
                            UpdatedDate = new DateTime(2023, 3, 10, 15, 17, 10, 742, DateTimeKind.Local).AddTicks(5381)
                        },
                        new
                        {
                            Id = 38,
                            Amenity = "Odio modi odio rerum voluptas suscipit earum voluptatem.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9440),
                            Details = "Voluptas vel numquam voluptatem qui eum alias.",
                            ImageURL = "https://picsum.photos/640/480/?image=299",
                            Name = "Arlene Steuber I",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 990,
                            UpdatedDate = new DateTime(2023, 3, 3, 22, 50, 17, 375, DateTimeKind.Local).AddTicks(7412)
                        },
                        new
                        {
                            Id = 39,
                            Amenity = "Adipisci adipisci voluptatem deleniti saepe nemo itaque animi assumenda.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9520),
                            Details = "Perferendis assumenda illo fuga modi ut necessitatibus facere.",
                            ImageURL = "https://picsum.photos/640/480/?image=978",
                            Name = "Dr. Andrea Pfannerstill",
                            Occupancy = 6,
                            Rate = 3.0,
                            SqureFeet = 662,
                            UpdatedDate = new DateTime(2023, 4, 26, 20, 20, 2, 662, DateTimeKind.Local).AddTicks(2686)
                        },
                        new
                        {
                            Id = 40,
                            Amenity = "Non dolorem at odio.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9580),
                            Details = "Ea maiores quod architecto ad aut quo accusamus.",
                            ImageURL = "https://picsum.photos/640/480/?image=303",
                            Name = "Shelley Cormier Sr.",
                            Occupancy = 5,
                            Rate = 5.0,
                            SqureFeet = 844,
                            UpdatedDate = new DateTime(2022, 10, 5, 2, 52, 22, 181, DateTimeKind.Local).AddTicks(238)
                        },
                        new
                        {
                            Id = 41,
                            Amenity = "Ut omnis non iste sed aut quia dolores.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9630),
                            Details = "Eius omnis nostrum.",
                            ImageURL = "https://picsum.photos/640/480/?image=373",
                            Name = "Dr. Peggy Hudson",
                            Occupancy = 6,
                            Rate = 5.0,
                            SqureFeet = 97,
                            UpdatedDate = new DateTime(2023, 3, 8, 1, 35, 19, 567, DateTimeKind.Local).AddTicks(843)
                        },
                        new
                        {
                            Id = 42,
                            Amenity = "Saepe quibusdam minima non.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9680),
                            Details = "Excepturi recusandae itaque.",
                            ImageURL = "https://picsum.photos/640/480/?image=958",
                            Name = "Tami Ferry MD",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 960,
                            UpdatedDate = new DateTime(2022, 11, 23, 19, 5, 3, 709, DateTimeKind.Local).AddTicks(625)
                        },
                        new
                        {
                            Id = 43,
                            Amenity = "Architecto omnis nulla dolorem quia sit aut error.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9810),
                            Details = "Omnis aut cupiditate deleniti.",
                            ImageURL = "https://picsum.photos/640/480/?image=259",
                            Name = "Miss Spencer Okuneva",
                            Occupancy = 10,
                            Rate = 2.0,
                            SqureFeet = 422,
                            UpdatedDate = new DateTime(2023, 3, 7, 23, 22, 5, 311, DateTimeKind.Local).AddTicks(9681)
                        },
                        new
                        {
                            Id = 44,
                            Amenity = "Laudantium aperiam nobis vitae deleniti autem eaque quaerat.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9890),
                            Details = "Velit excepturi ut reprehenderit voluptatem eos quidem voluptatem atque aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=244",
                            Name = "Courtney Torp I",
                            Occupancy = 3,
                            Rate = 5.0,
                            SqureFeet = 198,
                            UpdatedDate = new DateTime(2022, 11, 1, 14, 48, 57, 425, DateTimeKind.Local).AddTicks(5714)
                        },
                        new
                        {
                            Id = 45,
                            Amenity = "Repellat officia libero sit nulla sapiente et quidem et.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 386, DateTimeKind.Local).AddTicks(9960),
                            Details = "Temporibus nihil voluptatem perspiciatis assumenda in velit animi.",
                            ImageURL = "https://picsum.photos/640/480/?image=324",
                            Name = "Emily Feil IV",
                            Occupancy = 7,
                            Rate = 4.0,
                            SqureFeet = 90,
                            UpdatedDate = new DateTime(2022, 12, 1, 0, 36, 6, 617, DateTimeKind.Local).AddTicks(9367)
                        },
                        new
                        {
                            Id = 46,
                            Amenity = "Expedita reiciendis nihil eveniet repellat.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(20),
                            Details = "Eos rerum molestiae eum dolorem.",
                            ImageURL = "https://picsum.photos/640/480/?image=838",
                            Name = "Josephine Kuphal Sr.",
                            Occupancy = 9,
                            Rate = 5.0,
                            SqureFeet = 643,
                            UpdatedDate = new DateTime(2023, 2, 6, 7, 50, 0, 957, DateTimeKind.Local).AddTicks(6088)
                        },
                        new
                        {
                            Id = 47,
                            Amenity = "Id tempore veritatis est blanditiis soluta deserunt id temporibus dolorem.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(80),
                            Details = "Delectus porro iusto odit aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=879",
                            Name = "Delores Mitchell PhD",
                            Occupancy = 5,
                            Rate = 2.0,
                            SqureFeet = 928,
                            UpdatedDate = new DateTime(2022, 11, 1, 1, 28, 29, 318, DateTimeKind.Local).AddTicks(8906)
                        },
                        new
                        {
                            Id = 48,
                            Amenity = "Beatae deleniti nobis suscipit assumenda esse rem eum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(170),
                            Details = "Dolores quo quasi sunt ut distinctio eum.",
                            ImageURL = "https://picsum.photos/640/480/?image=71",
                            Name = "Ms. Yvette Rutherford",
                            Occupancy = 6,
                            Rate = 2.0,
                            SqureFeet = 828,
                            UpdatedDate = new DateTime(2022, 9, 3, 11, 6, 7, 517, DateTimeKind.Local).AddTicks(9562)
                        },
                        new
                        {
                            Id = 49,
                            Amenity = "Nulla officiis tenetur natus qui numquam aspernatur non.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(240),
                            Details = "Ea aspernatur minima sunt eos quod voluptatem.",
                            ImageURL = "https://picsum.photos/640/480/?image=987",
                            Name = "Ms. Vanessa Heidenreich",
                            Occupancy = 6,
                            Rate = 3.0,
                            SqureFeet = 940,
                            UpdatedDate = new DateTime(2022, 8, 13, 2, 19, 37, 812, DateTimeKind.Local).AddTicks(3301)
                        },
                        new
                        {
                            Id = 50,
                            Amenity = "Dicta exercitationem et et aut voluptatem sapiente veritatis.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(300),
                            Details = "Autem rerum labore repellendus.",
                            ImageURL = "https://picsum.photos/640/480/?image=806",
                            Name = "Danny Cormier V",
                            Occupancy = 2,
                            Rate = 4.0,
                            SqureFeet = 619,
                            UpdatedDate = new DateTime(2022, 8, 13, 6, 5, 33, 0, DateTimeKind.Local).AddTicks(5889)
                        },
                        new
                        {
                            Id = 51,
                            Amenity = "A accusamus dolorem rerum voluptatem qui voluptates voluptas atque consequatur.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(380),
                            Details = "Aut deleniti consequatur adipisci consequatur laudantium omnis nulla ex aspernatur.",
                            ImageURL = "https://picsum.photos/640/480/?image=260",
                            Name = "Patsy Reichert V",
                            Occupancy = 5,
                            Rate = 1.0,
                            SqureFeet = 498,
                            UpdatedDate = new DateTime(2022, 6, 7, 19, 14, 48, 944, DateTimeKind.Local).AddTicks(8566)
                        },
                        new
                        {
                            Id = 52,
                            Amenity = "Quos nihil maxime.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(430),
                            Details = "Corporis in quos.",
                            ImageURL = "https://picsum.photos/640/480/?image=175",
                            Name = "Dr. Theodore Littel",
                            Occupancy = 6,
                            Rate = 1.0,
                            SqureFeet = 770,
                            UpdatedDate = new DateTime(2022, 7, 11, 7, 10, 46, 580, DateTimeKind.Local).AddTicks(5673)
                        },
                        new
                        {
                            Id = 53,
                            Amenity = "In placeat et ea molestias tenetur quo.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(490),
                            Details = "Amet ut architecto et.",
                            ImageURL = "https://picsum.photos/640/480/?image=538",
                            Name = "Ms. Rita Dickens",
                            Occupancy = 5,
                            Rate = 4.0,
                            SqureFeet = 456,
                            UpdatedDate = new DateTime(2023, 3, 24, 9, 13, 46, 686, DateTimeKind.Local).AddTicks(7510)
                        },
                        new
                        {
                            Id = 54,
                            Amenity = "Repudiandae fugit vitae iusto porro.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(540),
                            Details = "Quidem sint corrupti ut quasi.",
                            ImageURL = "https://picsum.photos/640/480/?image=499",
                            Name = "Dr. Doris Sawayn",
                            Occupancy = 4,
                            Rate = 5.0,
                            SqureFeet = 558,
                            UpdatedDate = new DateTime(2023, 5, 5, 13, 38, 39, 341, DateTimeKind.Local).AddTicks(4809)
                        },
                        new
                        {
                            Id = 55,
                            Amenity = "Ullam veniam debitis.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(620),
                            Details = "Facere vel qui pariatur nulla et eius ut nam qui.",
                            ImageURL = "https://picsum.photos/640/480/?image=457",
                            Name = "Mr. Rosalie Altenwerth",
                            Occupancy = 9,
                            Rate = 3.0,
                            SqureFeet = 448,
                            UpdatedDate = new DateTime(2022, 6, 25, 11, 2, 46, 568, DateTimeKind.Local).AddTicks(4406)
                        },
                        new
                        {
                            Id = 56,
                            Amenity = "Illum et repudiandae fugiat.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(680),
                            Details = "Et sit illum corporis magni.",
                            ImageURL = "https://picsum.photos/640/480/?image=66",
                            Name = "Mr. Dominic Borer",
                            Occupancy = 1,
                            Rate = 4.0,
                            SqureFeet = 361,
                            UpdatedDate = new DateTime(2023, 1, 16, 8, 37, 7, 751, DateTimeKind.Local).AddTicks(8467)
                        },
                        new
                        {
                            Id = 57,
                            Amenity = "Culpa illo quaerat voluptatibus reprehenderit iusto.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(740),
                            Details = "Accusamus et sed dolor sapiente qui.",
                            ImageURL = "https://picsum.photos/640/480/?image=643",
                            Name = "Cedric Sauer V",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 698,
                            UpdatedDate = new DateTime(2022, 9, 6, 6, 58, 29, 309, DateTimeKind.Local).AddTicks(8942)
                        },
                        new
                        {
                            Id = 58,
                            Amenity = "Veritatis impedit voluptates facilis sapiente repudiandae laudantium fugit rerum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(800),
                            Details = "Inventore ab sed aut commodi.",
                            ImageURL = "https://picsum.photos/640/480/?image=69",
                            Name = "Mrs. James Howell",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 908,
                            UpdatedDate = new DateTime(2023, 1, 21, 15, 42, 6, 394, DateTimeKind.Local).AddTicks(8779)
                        },
                        new
                        {
                            Id = 59,
                            Amenity = "Voluptatum aut neque pariatur sint veniam maiores eum consequuntur.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(870),
                            Details = "Accusantium nemo saepe rerum dolor vel.",
                            ImageURL = "https://picsum.photos/640/480/?image=754",
                            Name = "Myron Stehr DDS",
                            Occupancy = 7,
                            Rate = 5.0,
                            SqureFeet = 803,
                            UpdatedDate = new DateTime(2023, 3, 3, 15, 49, 0, 439, DateTimeKind.Local).AddTicks(9735)
                        },
                        new
                        {
                            Id = 60,
                            Amenity = "Harum consequatur ab dolorem eos est qui vero voluptatibus assumenda.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(940),
                            Details = "Eaque facere est aliquid repellat ut vero at.",
                            ImageURL = "https://picsum.photos/640/480/?image=308",
                            Name = "Johanna Carroll V",
                            Occupancy = 8,
                            Rate = 3.0,
                            SqureFeet = 602,
                            UpdatedDate = new DateTime(2023, 3, 19, 23, 35, 17, 5, DateTimeKind.Local).AddTicks(3516)
                        },
                        new
                        {
                            Id = 61,
                            Amenity = "Expedita rerum occaecati ducimus odit.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1020),
                            Details = "Distinctio autem ea perferendis ducimus dolorem.",
                            ImageURL = "https://picsum.photos/640/480/?image=439",
                            Name = "Corey Raynor DVM",
                            Occupancy = 9,
                            Rate = 3.0,
                            SqureFeet = 337,
                            UpdatedDate = new DateTime(2022, 5, 18, 0, 20, 7, 710, DateTimeKind.Local).AddTicks(7174)
                        },
                        new
                        {
                            Id = 62,
                            Amenity = "Sit possimus aut quia voluptas itaque esse.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1090),
                            Details = "Ea nobis unde voluptatem repellendus esse molestias.",
                            ImageURL = "https://picsum.photos/640/480/?image=524",
                            Name = "Ms. Carolyn Lang",
                            Occupancy = 7,
                            Rate = 4.0,
                            SqureFeet = 587,
                            UpdatedDate = new DateTime(2023, 2, 17, 22, 34, 52, 82, DateTimeKind.Local).AddTicks(5290)
                        },
                        new
                        {
                            Id = 63,
                            Amenity = "Non aspernatur et sequi a non laudantium voluptatem rerum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1150),
                            Details = "Et unde reiciendis ipsam.",
                            ImageURL = "https://picsum.photos/640/480/?image=1009",
                            Name = "Ms. Daryl Huels",
                            Occupancy = 7,
                            Rate = 1.0,
                            SqureFeet = 956,
                            UpdatedDate = new DateTime(2023, 3, 6, 20, 31, 0, 872, DateTimeKind.Local).AddTicks(2695)
                        },
                        new
                        {
                            Id = 64,
                            Amenity = "Voluptas saepe veritatis nam dolorem soluta quo atque laborum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1210),
                            Details = "Rerum nemo et suscipit.",
                            ImageURL = "https://picsum.photos/640/480/?image=998",
                            Name = "Marco Kuphal Sr.",
                            Occupancy = 10,
                            Rate = 2.0,
                            SqureFeet = 41,
                            UpdatedDate = new DateTime(2022, 5, 26, 21, 44, 19, 803, DateTimeKind.Local).AddTicks(6850)
                        },
                        new
                        {
                            Id = 65,
                            Amenity = "Possimus iste qui sit consequatur ducimus consequuntur facere maiores.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1280),
                            Details = "Consequatur sit maxime deleniti adipisci porro.",
                            ImageURL = "https://picsum.photos/640/480/?image=1080",
                            Name = "Miss Marian Mante",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 965,
                            UpdatedDate = new DateTime(2023, 4, 16, 23, 4, 5, 339, DateTimeKind.Local).AddTicks(9515)
                        },
                        new
                        {
                            Id = 66,
                            Amenity = "Fuga ab et qui aut soluta nesciunt asperiores.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1350),
                            Details = "Molestiae temporibus non sed quibusdam omnis dolorem quia porro quia.",
                            ImageURL = "https://picsum.photos/640/480/?image=531",
                            Name = "Helen Schamberger I",
                            Occupancy = 3,
                            Rate = 1.0,
                            SqureFeet = 379,
                            UpdatedDate = new DateTime(2022, 7, 11, 14, 37, 39, 669, DateTimeKind.Local).AddTicks(7830)
                        },
                        new
                        {
                            Id = 67,
                            Amenity = "Ea blanditiis fugiat dignissimos quia.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1430),
                            Details = "Alias ut quaerat ea nesciunt debitis repudiandae.",
                            ImageURL = "https://picsum.photos/640/480/?image=11",
                            Name = "Winston Stracke V",
                            Occupancy = 6,
                            Rate = 1.0,
                            SqureFeet = 920,
                            UpdatedDate = new DateTime(2022, 7, 8, 9, 27, 48, 106, DateTimeKind.Local).AddTicks(9099)
                        },
                        new
                        {
                            Id = 68,
                            Amenity = "Omnis aut dolores rerum autem cumque reiciendis voluptatem.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1490),
                            Details = "Sint voluptas quo cumque debitis.",
                            ImageURL = "https://picsum.photos/640/480/?image=481",
                            Name = "Ms. Desiree Bruen",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 274,
                            UpdatedDate = new DateTime(2022, 11, 5, 15, 42, 58, 545, DateTimeKind.Local).AddTicks(2276)
                        },
                        new
                        {
                            Id = 69,
                            Amenity = "Dolores molestiae fugiat aperiam corrupti dolor vero consequatur.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1550),
                            Details = "Id officia sint est dicta eaque.",
                            ImageURL = "https://picsum.photos/640/480/?image=389",
                            Name = "Miss Rochelle Krajcik",
                            Occupancy = 3,
                            Rate = 1.0,
                            SqureFeet = 767,
                            UpdatedDate = new DateTime(2022, 5, 12, 22, 54, 50, 431, DateTimeKind.Local).AddTicks(2362)
                        },
                        new
                        {
                            Id = 70,
                            Amenity = "Magnam labore sed earum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1610),
                            Details = "Aut officia omnis velit.",
                            ImageURL = "https://picsum.photos/640/480/?image=927",
                            Name = "Ms. Christine Donnelly",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 352,
                            UpdatedDate = new DateTime(2022, 6, 1, 5, 22, 4, 774, DateTimeKind.Local).AddTicks(8861)
                        },
                        new
                        {
                            Id = 71,
                            Amenity = "Eius quos ut commodi vel et quia velit ab.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1680),
                            Details = "Quis eaque praesentium ut earum alias quia.",
                            ImageURL = "https://picsum.photos/640/480/?image=652",
                            Name = "Ms. Edith Schoen",
                            Occupancy = 10,
                            Rate = 4.0,
                            SqureFeet = 817,
                            UpdatedDate = new DateTime(2023, 3, 27, 1, 33, 52, 50, DateTimeKind.Local).AddTicks(8487)
                        },
                        new
                        {
                            Id = 72,
                            Amenity = "Quisquam quia alias temporibus dicta non deserunt dolores ipsam.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1750),
                            Details = "Molestias quasi voluptatem eos natus ratione vel non deserunt.",
                            ImageURL = "https://picsum.photos/640/480/?image=664",
                            Name = "Ms. Crystal Schimmel",
                            Occupancy = 3,
                            Rate = 3.0,
                            SqureFeet = 25,
                            UpdatedDate = new DateTime(2022, 12, 2, 13, 23, 19, 973, DateTimeKind.Local).AddTicks(3983)
                        },
                        new
                        {
                            Id = 73,
                            Amenity = "Labore exercitationem non illum mollitia et perferendis ut in labore.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1840),
                            Details = "Magnam perferendis mollitia ad aut eum dolor.",
                            ImageURL = "https://picsum.photos/640/480/?image=53",
                            Name = "Miss Lewis O'Reilly",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 880,
                            UpdatedDate = new DateTime(2023, 1, 31, 15, 32, 12, 384, DateTimeKind.Local).AddTicks(1104)
                        },
                        new
                        {
                            Id = 74,
                            Amenity = "Asperiores id voluptates.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1890),
                            Details = "Eum mollitia eligendi qui.",
                            ImageURL = "https://picsum.photos/640/480/?image=265",
                            Name = "Mrs. Emanuel White",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 504,
                            UpdatedDate = new DateTime(2022, 9, 30, 18, 31, 6, 336, DateTimeKind.Local).AddTicks(2414)
                        },
                        new
                        {
                            Id = 75,
                            Amenity = "Quia dolorum et quas sint repellendus minima earum possimus distinctio.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(1960),
                            Details = "Illum alias dolor et iusto beatae aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=1084",
                            Name = "Dianna Doyle III",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 554,
                            UpdatedDate = new DateTime(2023, 3, 5, 13, 24, 17, 513, DateTimeKind.Local).AddTicks(2228)
                        },
                        new
                        {
                            Id = 76,
                            Amenity = "Ea at est voluptatem beatae ipsum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2030),
                            Details = "Dicta omnis ducimus nisi autem praesentium ratione non.",
                            ImageURL = "https://picsum.photos/640/480/?image=660",
                            Name = "Miss Jasmine Abbott",
                            Occupancy = 4,
                            Rate = 5.0,
                            SqureFeet = 900,
                            UpdatedDate = new DateTime(2023, 2, 13, 4, 57, 8, 281, DateTimeKind.Local).AddTicks(7614)
                        },
                        new
                        {
                            Id = 77,
                            Amenity = "Corrupti inventore id voluptas et labore itaque.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2090),
                            Details = "Provident ipsum vero quia animi perspiciatis fugiat.",
                            ImageURL = "https://picsum.photos/640/480/?image=17",
                            Name = "Dr. Crystal Bayer",
                            Occupancy = 9,
                            Rate = 2.0,
                            SqureFeet = 411,
                            UpdatedDate = new DateTime(2022, 7, 25, 16, 58, 38, 99, DateTimeKind.Local).AddTicks(2334)
                        },
                        new
                        {
                            Id = 78,
                            Amenity = "Ab debitis sed assumenda labore et.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2160),
                            Details = "Sint consectetur ipsa praesentium quam facere porro atque reprehenderit sint.",
                            ImageURL = "https://picsum.photos/640/480/?image=191",
                            Name = "Miss Felipe Ziemann",
                            Occupancy = 1,
                            Rate = 4.0,
                            SqureFeet = 162,
                            UpdatedDate = new DateTime(2022, 7, 10, 17, 51, 16, 971, DateTimeKind.Local).AddTicks(1562)
                        },
                        new
                        {
                            Id = 79,
                            Amenity = "Dolores sed qui quibusdam voluptate minima optio molestiae.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2240),
                            Details = "Alias repudiandae doloribus voluptatum.",
                            ImageURL = "https://picsum.photos/640/480/?image=96",
                            Name = "Mrs. Steven Legros",
                            Occupancy = 2,
                            Rate = 3.0,
                            SqureFeet = 777,
                            UpdatedDate = new DateTime(2022, 10, 14, 4, 34, 12, 624, DateTimeKind.Local).AddTicks(6311)
                        },
                        new
                        {
                            Id = 80,
                            Amenity = "Deleniti dicta qui est explicabo.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2300),
                            Details = "Ipsum unde aut necessitatibus molestias aut ratione.",
                            ImageURL = "https://picsum.photos/640/480/?image=1016",
                            Name = "Mr. Tommy Nienow",
                            Occupancy = 3,
                            Rate = 1.0,
                            SqureFeet = 621,
                            UpdatedDate = new DateTime(2022, 11, 11, 21, 21, 5, 528, DateTimeKind.Local).AddTicks(5033)
                        },
                        new
                        {
                            Id = 81,
                            Amenity = "Facilis tempore natus et exercitationem ducimus.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2360),
                            Details = "Laborum autem non consequatur.",
                            ImageURL = "https://picsum.photos/640/480/?image=500",
                            Name = "Willard Crona II",
                            Occupancy = 2,
                            Rate = 5.0,
                            SqureFeet = 612,
                            UpdatedDate = new DateTime(2022, 10, 12, 15, 51, 7, 369, DateTimeKind.Local).AddTicks(7417)
                        },
                        new
                        {
                            Id = 82,
                            Amenity = "Est amet deleniti eos laborum qui ex ut.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2420),
                            Details = "Ad ut fugit pariatur.",
                            ImageURL = "https://picsum.photos/640/480/?image=909",
                            Name = "Willie Monahan DDS",
                            Occupancy = 9,
                            Rate = 4.0,
                            SqureFeet = 163,
                            UpdatedDate = new DateTime(2022, 9, 17, 16, 54, 17, 274, DateTimeKind.Local).AddTicks(2418)
                        },
                        new
                        {
                            Id = 83,
                            Amenity = "Aut eligendi ex illo est.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2490),
                            Details = "Illum nisi id nihil rerum vitae exercitationem velit recusandae consequatur.",
                            ImageURL = "https://picsum.photos/640/480/?image=36",
                            Name = "Alexandra Ryan V",
                            Occupancy = 4,
                            Rate = 3.0,
                            SqureFeet = 397,
                            UpdatedDate = new DateTime(2023, 4, 3, 16, 18, 16, 284, DateTimeKind.Local).AddTicks(7164)
                        },
                        new
                        {
                            Id = 84,
                            Amenity = "Rerum animi perferendis quia et numquam nostrum ea velit officia.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2560),
                            Details = "Modi alias harum quo facere illo sint porro.",
                            ImageURL = "https://picsum.photos/640/480/?image=285",
                            Name = "Dr. Delbert Bogan",
                            Occupancy = 10,
                            Rate = 1.0,
                            SqureFeet = 76,
                            UpdatedDate = new DateTime(2022, 5, 23, 0, 13, 8, 439, DateTimeKind.Local).AddTicks(6537)
                        },
                        new
                        {
                            Id = 85,
                            Amenity = "Natus est rerum.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2620),
                            Details = "Reprehenderit est est.",
                            ImageURL = "https://picsum.photos/640/480/?image=116",
                            Name = "Mr. Gerald Gleason",
                            Occupancy = 2,
                            Rate = 5.0,
                            SqureFeet = 334,
                            UpdatedDate = new DateTime(2022, 5, 20, 11, 52, 7, 672, DateTimeKind.Local).AddTicks(7878)
                        },
                        new
                        {
                            Id = 86,
                            Amenity = "Nihil consequatur excepturi.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2680),
                            Details = "Tenetur occaecati voluptas voluptatem.",
                            ImageURL = "https://picsum.photos/640/480/?image=22",
                            Name = "Marianne Metz V",
                            Occupancy = 4,
                            Rate = 5.0,
                            SqureFeet = 410,
                            UpdatedDate = new DateTime(2022, 9, 25, 1, 10, 13, 308, DateTimeKind.Local).AddTicks(9778)
                        },
                        new
                        {
                            Id = 87,
                            Amenity = "Rem voluptatibus nesciunt.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(2730),
                            Details = "Dolores saepe perferendis et numquam et.",
                            ImageURL = "https://picsum.photos/640/480/?image=412",
                            Name = "Ken Morissette DVM",
                            Occupancy = 6,
                            Rate = 2.0,
                            SqureFeet = 817,
                            UpdatedDate = new DateTime(2022, 12, 13, 4, 9, 57, 102, DateTimeKind.Local).AddTicks(3610)
                        },
                        new
                        {
                            Id = 88,
                            Amenity = "Fugiat rerum excepturi qui aut impedit aut maxime dolor.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3150),
                            Details = "Provident aut necessitatibus et saepe non commodi odio unde minima.",
                            ImageURL = "https://picsum.photos/640/480/?image=323",
                            Name = "Lisa Kuhlman MD",
                            Occupancy = 1,
                            Rate = 2.0,
                            SqureFeet = 886,
                            UpdatedDate = new DateTime(2022, 7, 27, 21, 53, 21, 523, DateTimeKind.Local).AddTicks(486)
                        },
                        new
                        {
                            Id = 89,
                            Amenity = "Rerum quas consequuntur tempore minus.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3210),
                            Details = "Odit optio pariatur molestiae atque.",
                            ImageURL = "https://picsum.photos/640/480/?image=647",
                            Name = "Geoffrey Bosco II",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 197,
                            UpdatedDate = new DateTime(2023, 1, 16, 14, 22, 34, 330, DateTimeKind.Local).AddTicks(3026)
                        },
                        new
                        {
                            Id = 90,
                            Amenity = "Ut itaque et quaerat et totam sint cum et.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3270),
                            Details = "Fugit sit deserunt.",
                            ImageURL = "https://picsum.photos/640/480/?image=969",
                            Name = "Dr. Wendy Terry",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 169,
                            UpdatedDate = new DateTime(2022, 12, 4, 5, 24, 22, 351, DateTimeKind.Local).AddTicks(8945)
                        },
                        new
                        {
                            Id = 91,
                            Amenity = "Quo maxime qui rem animi et repellat rem ut.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3340),
                            Details = "Doloremque harum sunt dolor sint aut magni et.",
                            ImageURL = "https://picsum.photos/640/480/?image=586",
                            Name = "Amos Yost III",
                            Occupancy = 9,
                            Rate = 4.0,
                            SqureFeet = 337,
                            UpdatedDate = new DateTime(2023, 1, 31, 5, 25, 22, 943, DateTimeKind.Local).AddTicks(6040)
                        },
                        new
                        {
                            Id = 92,
                            Amenity = "Laborum repudiandae eos enim magni placeat est eum quia quam.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3440),
                            Details = "Et voluptas sapiente cupiditate dolore est dicta eligendi in.",
                            ImageURL = "https://picsum.photos/640/480/?image=599",
                            Name = "Ms. Margie Schroeder",
                            Occupancy = 8,
                            Rate = 1.0,
                            SqureFeet = 208,
                            UpdatedDate = new DateTime(2022, 8, 23, 18, 59, 22, 683, DateTimeKind.Local).AddTicks(1976)
                        },
                        new
                        {
                            Id = 93,
                            Amenity = "Debitis accusantium assumenda sit veniam voluptatem aut ut doloremque quod.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3520),
                            Details = "Pariatur culpa dolorem ipsum non nihil doloribus dolorem maxime sunt.",
                            ImageURL = "https://picsum.photos/640/480/?image=9",
                            Name = "Roberta Zulauf MD",
                            Occupancy = 2,
                            Rate = 1.0,
                            SqureFeet = 831,
                            UpdatedDate = new DateTime(2023, 3, 26, 21, 51, 24, 667, DateTimeKind.Local).AddTicks(3682)
                        },
                        new
                        {
                            Id = 94,
                            Amenity = "Repellendus officia repellat sit quo voluptates deleniti ipsam iure.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3580),
                            Details = "Enim sint minus in corporis.",
                            ImageURL = "https://picsum.photos/640/480/?image=945",
                            Name = "Emily Satterfield DVM",
                            Occupancy = 1,
                            Rate = 3.0,
                            SqureFeet = 46,
                            UpdatedDate = new DateTime(2023, 5, 5, 17, 57, 18, 828, DateTimeKind.Local).AddTicks(9308)
                        },
                        new
                        {
                            Id = 95,
                            Amenity = "Quibusdam placeat fugiat fugiat.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3640),
                            Details = "Qui ut repellendus modi ad possimus.",
                            ImageURL = "https://picsum.photos/640/480/?image=1028",
                            Name = "Miss Sherman Luettgen",
                            Occupancy = 3,
                            Rate = 2.0,
                            SqureFeet = 46,
                            UpdatedDate = new DateTime(2023, 1, 8, 15, 53, 36, 117, DateTimeKind.Local).AddTicks(6137)
                        },
                        new
                        {
                            Id = 96,
                            Amenity = "Labore quaerat omnis assumenda.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3690),
                            Details = "Eum ut ea dolores repudiandae.",
                            ImageURL = "https://picsum.photos/640/480/?image=414",
                            Name = "Marcella West DVM",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 539,
                            UpdatedDate = new DateTime(2022, 11, 30, 12, 21, 48, 889, DateTimeKind.Local).AddTicks(910)
                        },
                        new
                        {
                            Id = 97,
                            Amenity = "Laboriosam omnis a ut enim omnis.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3750),
                            Details = "Distinctio dolorem sapiente maxime ipsum asperiores.",
                            ImageURL = "https://picsum.photos/640/480/?image=97",
                            Name = "Lowell Stamm III",
                            Occupancy = 2,
                            Rate = 1.0,
                            SqureFeet = 419,
                            UpdatedDate = new DateTime(2022, 12, 28, 21, 23, 23, 385, DateTimeKind.Local).AddTicks(9634)
                        },
                        new
                        {
                            Id = 98,
                            Amenity = "A et a omnis explicabo magni corporis et dicta maxime.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3840),
                            Details = "Qui debitis nulla animi doloribus asperiores aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=600",
                            Name = "Margie Runolfsdottir I",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 889,
                            UpdatedDate = new DateTime(2022, 8, 19, 23, 47, 39, 267, DateTimeKind.Local).AddTicks(418)
                        },
                        new
                        {
                            Id = 99,
                            Amenity = "Accusantium sit accusamus voluptatem hic dolor quis.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3900),
                            Details = "Est architecto consequatur tempore eveniet voluptatem non.",
                            ImageURL = "https://picsum.photos/640/480/?image=584",
                            Name = "Beth Bernhard V",
                            Occupancy = 6,
                            Rate = 2.0,
                            SqureFeet = 613,
                            UpdatedDate = new DateTime(2022, 12, 22, 18, 33, 30, 801, DateTimeKind.Local).AddTicks(6345)
                        },
                        new
                        {
                            Id = 100,
                            Amenity = "Magnam cupiditate labore.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 53, 47, 387, DateTimeKind.Local).AddTicks(3950),
                            Details = "Illo ea fugit aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=748",
                            Name = "Nick Hane III",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 690,
                            UpdatedDate = new DateTime(2023, 3, 12, 3, 22, 2, 308, DateTimeKind.Local).AddTicks(7034)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
