// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa_API.Data;

#nullable disable

namespace Villa_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230508135528_AddVillaTableWithBogus2")]
    partial class AddVillaTableWithBogus2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SqureFeet")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Quo cumque nisi voluptatem possimus incidunt dolorum.",
                            CreatedDate = new DateTime(2023, 5, 7, 20, 42, 40, 850, DateTimeKind.Local).AddTicks(8990),
                            Details = "Eos voluptatem labore.",
                            ImageURL = "https://picsum.photos/640/480/?image=716",
                            Name = "Jan Bernhard I",
                            Occupancy = 5,
                            Rate = 4.0,
                            SqureFeet = 430,
                            UpdatedDate = new DateTime(2023, 1, 13, 23, 57, 26, 468, DateTimeKind.Local).AddTicks(1761)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Beatae magnam doloribus.",
                            CreatedDate = new DateTime(2023, 5, 8, 9, 42, 6, 147, DateTimeKind.Local).AddTicks(1168),
                            Details = "Qui ut amet voluptatem.",
                            ImageURL = "https://picsum.photos/640/480/?image=726",
                            Name = "Elsa Heaney DVM",
                            Occupancy = 4,
                            Rate = 4.0,
                            SqureFeet = 412,
                            UpdatedDate = new DateTime(2022, 6, 1, 12, 42, 56, 251, DateTimeKind.Local).AddTicks(53)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Ipsum velit enim neque veniam sed ea dolore nam excepturi.",
                            CreatedDate = new DateTime(2023, 5, 7, 23, 26, 32, 736, DateTimeKind.Local).AddTicks(7332),
                            Details = "Incidunt debitis temporibus omnis ut cumque deleniti.",
                            ImageURL = "https://picsum.photos/640/480/?image=969",
                            Name = "Juan Renner IV",
                            Occupancy = 8,
                            Rate = 4.0,
                            SqureFeet = 679,
                            UpdatedDate = new DateTime(2022, 9, 25, 8, 20, 6, 114, DateTimeKind.Local).AddTicks(4430)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Consequatur aliquam facilis ab eum voluptatem magnam.",
                            CreatedDate = new DateTime(2023, 5, 7, 20, 29, 10, 574, DateTimeKind.Local).AddTicks(8794),
                            Details = "Ullam ipsa nemo eveniet qui ipsa et.",
                            ImageURL = "https://picsum.photos/640/480/?image=15",
                            Name = "Ms. Michael Luettgen",
                            Occupancy = 1,
                            Rate = 1.0,
                            SqureFeet = 122,
                            UpdatedDate = new DateTime(2023, 4, 26, 1, 46, 57, 28, DateTimeKind.Local).AddTicks(3813)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Ut consequatur est.",
                            CreatedDate = new DateTime(2023, 5, 8, 2, 46, 44, 315, DateTimeKind.Local).AddTicks(682),
                            Details = "Architecto quaerat doloribus facilis sit maxime.",
                            ImageURL = "https://picsum.photos/640/480/?image=78",
                            Name = "Ms. Felix Schmitt",
                            Occupancy = 5,
                            Rate = 3.0,
                            SqureFeet = 100,
                            UpdatedDate = new DateTime(2022, 6, 25, 9, 32, 34, 936, DateTimeKind.Local).AddTicks(536)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Modi adipisci et.",
                            CreatedDate = new DateTime(2023, 5, 7, 22, 37, 1, 450, DateTimeKind.Local).AddTicks(3227),
                            Details = "A aut quis quidem.",
                            ImageURL = "https://picsum.photos/640/480/?image=993",
                            Name = "Audrey Mohr Jr.",
                            Occupancy = 4,
                            Rate = 5.0,
                            SqureFeet = 197,
                            UpdatedDate = new DateTime(2022, 10, 29, 14, 57, 54, 711, DateTimeKind.Local).AddTicks(3633)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Repudiandae dolores aut quo velit ducimus ut eligendi.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 34, 42, 267, DateTimeKind.Local).AddTicks(9157),
                            Details = "Architecto animi et molestias velit ipsa animi quas vero.",
                            ImageURL = "https://picsum.photos/640/480/?image=255",
                            Name = "Ella Koss Jr.",
                            Occupancy = 2,
                            Rate = 3.0,
                            SqureFeet = 685,
                            UpdatedDate = new DateTime(2022, 12, 26, 0, 53, 7, 569, DateTimeKind.Local).AddTicks(3518)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Et laboriosam aut totam autem ipsam labore.",
                            CreatedDate = new DateTime(2023, 5, 8, 8, 7, 43, 862, DateTimeKind.Local).AddTicks(1961),
                            Details = "Placeat totam ab in culpa voluptas molestiae.",
                            ImageURL = "https://picsum.photos/640/480/?image=33",
                            Name = "Pam Boyer III",
                            Occupancy = 10,
                            Rate = 1.0,
                            SqureFeet = 579,
                            UpdatedDate = new DateTime(2023, 2, 21, 0, 29, 18, 305, DateTimeKind.Local).AddTicks(5270)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Quia veritatis dignissimos laborum nostrum fugiat.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 44, 14, 272, DateTimeKind.Local).AddTicks(9518),
                            Details = "Sit non nulla.",
                            ImageURL = "https://picsum.photos/640/480/?image=336",
                            Name = "Mr. Miriam Homenick",
                            Occupancy = 10,
                            Rate = 2.0,
                            SqureFeet = 647,
                            UpdatedDate = new DateTime(2022, 6, 23, 4, 0, 36, 121, DateTimeKind.Local).AddTicks(9576)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Sequi libero labore non.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 59, 1, 990, DateTimeKind.Local).AddTicks(4081),
                            Details = "Dolore deserunt quia.",
                            ImageURL = "https://picsum.photos/640/480/?image=468",
                            Name = "Mrs. Rachel Hermiston",
                            Occupancy = 5,
                            Rate = 5.0,
                            SqureFeet = 725,
                            UpdatedDate = new DateTime(2022, 7, 15, 21, 15, 9, 939, DateTimeKind.Local).AddTicks(9385)
                        },
                        new
                        {
                            Id = 11,
                            Amenity = "Aspernatur perspiciatis optio sapiente iure eveniet excepturi asperiores ipsam nobis.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 25, 49, 195, DateTimeKind.Local).AddTicks(4154),
                            Details = "Consequatur blanditiis nesciunt voluptates in.",
                            ImageURL = "https://picsum.photos/640/480/?image=537",
                            Name = "Anna Wintheiser II",
                            Occupancy = 2,
                            Rate = 4.0,
                            SqureFeet = 965,
                            UpdatedDate = new DateTime(2022, 12, 25, 11, 33, 7, 952, DateTimeKind.Local).AddTicks(3189)
                        },
                        new
                        {
                            Id = 12,
                            Amenity = "Maiores velit nihil repellat alias consequatur aliquid.",
                            CreatedDate = new DateTime(2023, 5, 8, 10, 22, 32, 556, DateTimeKind.Local).AddTicks(3433),
                            Details = "Quaerat consequatur reiciendis ab unde ut qui quas voluptates.",
                            ImageURL = "https://picsum.photos/640/480/?image=565",
                            Name = "Madeline Weimann II",
                            Occupancy = 3,
                            Rate = 5.0,
                            SqureFeet = 896,
                            UpdatedDate = new DateTime(2022, 10, 12, 16, 38, 59, 821, DateTimeKind.Local).AddTicks(9563)
                        },
                        new
                        {
                            Id = 13,
                            Amenity = "Eum consequatur aut neque pariatur.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 31, 20, 6, DateTimeKind.Local).AddTicks(5986),
                            Details = "Vel est quasi amet corrupti similique cumque.",
                            ImageURL = "https://picsum.photos/640/480/?image=544",
                            Name = "Ms. Belinda Ledner",
                            Occupancy = 10,
                            Rate = 1.0,
                            SqureFeet = 670,
                            UpdatedDate = new DateTime(2022, 9, 14, 4, 47, 8, 97, DateTimeKind.Local).AddTicks(2652)
                        },
                        new
                        {
                            Id = 14,
                            Amenity = "Qui porro sint corporis est quia quo fugit voluptatum.",
                            CreatedDate = new DateTime(2023, 5, 8, 14, 41, 55, 951, DateTimeKind.Local).AddTicks(5839),
                            Details = "Temporibus eligendi non nulla qui atque explicabo.",
                            ImageURL = "https://picsum.photos/640/480/?image=629",
                            Name = "Madeline Purdy IV",
                            Occupancy = 7,
                            Rate = 5.0,
                            SqureFeet = 775,
                            UpdatedDate = new DateTime(2022, 9, 7, 5, 22, 12, 454, DateTimeKind.Local).AddTicks(2098)
                        },
                        new
                        {
                            Id = 15,
                            Amenity = "Doloribus voluptatum at et earum unde reprehenderit pariatur nemo.",
                            CreatedDate = new DateTime(2023, 5, 8, 14, 36, 5, 493, DateTimeKind.Local).AddTicks(4652),
                            Details = "Alias rerum porro aliquid qui et officiis consectetur.",
                            ImageURL = "https://picsum.photos/640/480/?image=566",
                            Name = "Roman Rohan Jr.",
                            Occupancy = 10,
                            Rate = 2.0,
                            SqureFeet = 321,
                            UpdatedDate = new DateTime(2022, 7, 6, 4, 46, 21, 826, DateTimeKind.Local).AddTicks(8152)
                        },
                        new
                        {
                            Id = 16,
                            Amenity = "Tempore et reiciendis.",
                            CreatedDate = new DateTime(2023, 5, 7, 23, 21, 42, 223, DateTimeKind.Local).AddTicks(1897),
                            Details = "Laboriosam vel deserunt et ut vel quas suscipit illo.",
                            ImageURL = "https://picsum.photos/640/480/?image=562",
                            Name = "Yolanda VonRueden III",
                            Occupancy = 7,
                            Rate = 5.0,
                            SqureFeet = 973,
                            UpdatedDate = new DateTime(2022, 12, 20, 8, 44, 54, 595, DateTimeKind.Local).AddTicks(2700)
                        },
                        new
                        {
                            Id = 17,
                            Amenity = "Est ipsa qui aut non numquam illo hic nesciunt.",
                            CreatedDate = new DateTime(2023, 5, 7, 22, 1, 26, 941, DateTimeKind.Local).AddTicks(5466),
                            Details = "Quia et reprehenderit dignissimos corporis.",
                            ImageURL = "https://picsum.photos/640/480/?image=820",
                            Name = "Terence Larkin PhD",
                            Occupancy = 8,
                            Rate = 1.0,
                            SqureFeet = 830,
                            UpdatedDate = new DateTime(2022, 7, 24, 9, 32, 36, 571, DateTimeKind.Local).AddTicks(5235)
                        },
                        new
                        {
                            Id = 18,
                            Amenity = "Nemo ratione ea dolorum natus in odit est deserunt.",
                            CreatedDate = new DateTime(2023, 5, 8, 8, 1, 40, 259, DateTimeKind.Local).AddTicks(5924),
                            Details = "Cum similique earum molestias magni aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=840",
                            Name = "Kelli Robel MD",
                            Occupancy = 1,
                            Rate = 2.0,
                            SqureFeet = 519,
                            UpdatedDate = new DateTime(2022, 6, 13, 2, 12, 19, 358, DateTimeKind.Local).AddTicks(8269)
                        },
                        new
                        {
                            Id = 19,
                            Amenity = "Dolorum ab ullam alias non et sunt.",
                            CreatedDate = new DateTime(2023, 5, 8, 4, 11, 36, 194, DateTimeKind.Local).AddTicks(1689),
                            Details = "Aut dolor consequatur distinctio.",
                            ImageURL = "https://picsum.photos/640/480/?image=567",
                            Name = "Mr. Melody Blanda",
                            Occupancy = 2,
                            Rate = 2.0,
                            SqureFeet = 250,
                            UpdatedDate = new DateTime(2022, 10, 23, 3, 52, 23, 442, DateTimeKind.Local).AddTicks(5217)
                        },
                        new
                        {
                            Id = 20,
                            Amenity = "Rem officia nihil inventore enim sed itaque.",
                            CreatedDate = new DateTime(2023, 5, 8, 1, 19, 37, 498, DateTimeKind.Local).AddTicks(9732),
                            Details = "Voluptate distinctio consequatur adipisci nam.",
                            ImageURL = "https://picsum.photos/640/480/?image=810",
                            Name = "Ms. Nadine Blanda",
                            Occupancy = 8,
                            Rate = 3.0,
                            SqureFeet = 484,
                            UpdatedDate = new DateTime(2022, 11, 25, 9, 25, 50, 979, DateTimeKind.Local).AddTicks(2998)
                        },
                        new
                        {
                            Id = 21,
                            Amenity = "Et explicabo similique.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 32, 50, 940, DateTimeKind.Local).AddTicks(8885),
                            Details = "Sit error voluptates omnis consectetur excepturi praesentium.",
                            ImageURL = "https://picsum.photos/640/480/?image=1070",
                            Name = "Mr. Samantha Rohan",
                            Occupancy = 5,
                            Rate = 5.0,
                            SqureFeet = 632,
                            UpdatedDate = new DateTime(2022, 6, 14, 19, 35, 35, 249, DateTimeKind.Local).AddTicks(414)
                        },
                        new
                        {
                            Id = 22,
                            Amenity = "In officiis et voluptatibus omnis alias omnis qui.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 33, 9, 814, DateTimeKind.Local).AddTicks(2414),
                            Details = "Qui unde asperiores provident delectus ut sequi dolor.",
                            ImageURL = "https://picsum.photos/640/480/?image=1057",
                            Name = "Ms. Josh Nolan",
                            Occupancy = 10,
                            Rate = 5.0,
                            SqureFeet = 492,
                            UpdatedDate = new DateTime(2023, 1, 4, 11, 42, 39, 685, DateTimeKind.Local).AddTicks(8079)
                        },
                        new
                        {
                            Id = 23,
                            Amenity = "Nostrum nisi necessitatibus optio quas.",
                            CreatedDate = new DateTime(2023, 5, 8, 3, 41, 52, 793, DateTimeKind.Local).AddTicks(515),
                            Details = "Mollitia placeat voluptate quae dolore impedit sed.",
                            ImageURL = "https://picsum.photos/640/480/?image=665",
                            Name = "Mr. Kathryn Bode",
                            Occupancy = 9,
                            Rate = 4.0,
                            SqureFeet = 712,
                            UpdatedDate = new DateTime(2023, 2, 25, 20, 50, 48, 41, DateTimeKind.Local).AddTicks(9745)
                        },
                        new
                        {
                            Id = 24,
                            Amenity = "Delectus aspernatur sunt hic autem vel optio.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 21, 47, 175, DateTimeKind.Local).AddTicks(773),
                            Details = "Tenetur numquam laboriosam dolorem eveniet esse numquam ex doloremque.",
                            ImageURL = "https://picsum.photos/640/480/?image=988",
                            Name = "Juanita Wyman DVM",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 10,
                            UpdatedDate = new DateTime(2022, 11, 18, 18, 40, 0, 565, DateTimeKind.Local).AddTicks(619)
                        },
                        new
                        {
                            Id = 25,
                            Amenity = "Nemo non facere vel id ducimus.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 54, 34, 727, DateTimeKind.Local).AddTicks(1237),
                            Details = "Qui dicta sint.",
                            ImageURL = "https://picsum.photos/640/480/?image=692",
                            Name = "Belinda Turner Jr.",
                            Occupancy = 6,
                            Rate = 5.0,
                            SqureFeet = 6,
                            UpdatedDate = new DateTime(2022, 5, 29, 19, 26, 18, 134, DateTimeKind.Local).AddTicks(1309)
                        },
                        new
                        {
                            Id = 26,
                            Amenity = "Mollitia dolore hic quod quos voluptate.",
                            CreatedDate = new DateTime(2023, 5, 8, 13, 11, 53, 430, DateTimeKind.Local).AddTicks(9292),
                            Details = "Qui laudantium est minus illo et qui quo aperiam.",
                            ImageURL = "https://picsum.photos/640/480/?image=242",
                            Name = "Dr. Danielle Keeling",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 694,
                            UpdatedDate = new DateTime(2022, 10, 19, 6, 23, 31, 125, DateTimeKind.Local).AddTicks(1769)
                        },
                        new
                        {
                            Id = 27,
                            Amenity = "Ipsam ab sed dicta nemo quia exercitationem iure.",
                            CreatedDate = new DateTime(2023, 5, 7, 23, 12, 15, 214, DateTimeKind.Local).AddTicks(2059),
                            Details = "Eius aut dolore sunt ad quam et dolore laboriosam sint.",
                            ImageURL = "https://picsum.photos/640/480/?image=699",
                            Name = "Curtis Wisoky III",
                            Occupancy = 3,
                            Rate = 2.0,
                            SqureFeet = 479,
                            UpdatedDate = new DateTime(2023, 3, 5, 23, 0, 8, 111, DateTimeKind.Local).AddTicks(7355)
                        },
                        new
                        {
                            Id = 28,
                            Amenity = "Odit enim voluptas accusamus cumque ab.",
                            CreatedDate = new DateTime(2023, 5, 8, 4, 32, 45, 541, DateTimeKind.Local).AddTicks(9782),
                            Details = "Modi hic voluptatem nihil non harum officia consequatur ducimus.",
                            ImageURL = "https://picsum.photos/640/480/?image=7",
                            Name = "Miss Harriet Donnelly",
                            Occupancy = 4,
                            Rate = 3.0,
                            SqureFeet = 451,
                            UpdatedDate = new DateTime(2023, 1, 23, 5, 25, 59, 207, DateTimeKind.Local).AddTicks(2438)
                        },
                        new
                        {
                            Id = 29,
                            Amenity = "Adipisci veniam magnam.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 31, 21, 542, DateTimeKind.Local).AddTicks(5182),
                            Details = "In illo quibusdam nihil esse dolorum totam est.",
                            ImageURL = "https://picsum.photos/640/480/?image=1074",
                            Name = "Thelma Sauer PhD",
                            Occupancy = 10,
                            Rate = 4.0,
                            SqureFeet = 969,
                            UpdatedDate = new DateTime(2023, 3, 12, 12, 1, 7, 519, DateTimeKind.Local).AddTicks(6385)
                        },
                        new
                        {
                            Id = 30,
                            Amenity = "Eum ea ad sint quis et optio.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 9, 7, 951, DateTimeKind.Local).AddTicks(5308),
                            Details = "Nobis ratione debitis.",
                            ImageURL = "https://picsum.photos/640/480/?image=275",
                            Name = "Al Balistreri MD",
                            Occupancy = 3,
                            Rate = 2.0,
                            SqureFeet = 417,
                            UpdatedDate = new DateTime(2023, 3, 14, 20, 15, 55, 760, DateTimeKind.Local).AddTicks(2998)
                        },
                        new
                        {
                            Id = 31,
                            Amenity = "Itaque sed distinctio quas.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 2, 56, 375, DateTimeKind.Local).AddTicks(8351),
                            Details = "Quam quaerat magnam magni velit sed et molestias nesciunt.",
                            ImageURL = "https://picsum.photos/640/480/?image=202",
                            Name = "Mr. Frankie Hagenes",
                            Occupancy = 2,
                            Rate = 5.0,
                            SqureFeet = 741,
                            UpdatedDate = new DateTime(2023, 4, 13, 20, 50, 57, 264, DateTimeKind.Local).AddTicks(2781)
                        },
                        new
                        {
                            Id = 32,
                            Amenity = "Praesentium architecto rerum sunt impedit doloremque.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 16, 11, 411, DateTimeKind.Local).AddTicks(1061),
                            Details = "Dolorem quisquam libero quae rem reprehenderit sequi qui quisquam.",
                            ImageURL = "https://picsum.photos/640/480/?image=263",
                            Name = "Rick Walker DDS",
                            Occupancy = 10,
                            Rate = 4.0,
                            SqureFeet = 364,
                            UpdatedDate = new DateTime(2022, 6, 6, 7, 4, 22, 312, DateTimeKind.Local).AddTicks(8751)
                        },
                        new
                        {
                            Id = 33,
                            Amenity = "Officia aut in voluptas est expedita hic minima iste.",
                            CreatedDate = new DateTime(2023, 5, 7, 20, 44, 49, 543, DateTimeKind.Local).AddTicks(3998),
                            Details = "Dolor cum minus ea mollitia similique.",
                            ImageURL = "https://picsum.photos/640/480/?image=1058",
                            Name = "Milton Kertzmann Jr.",
                            Occupancy = 4,
                            Rate = 3.0,
                            SqureFeet = 60,
                            UpdatedDate = new DateTime(2022, 9, 16, 14, 35, 56, 212, DateTimeKind.Local).AddTicks(8848)
                        },
                        new
                        {
                            Id = 34,
                            Amenity = "Enim ex quam cumque.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 59, 11, 811, DateTimeKind.Local).AddTicks(8001),
                            Details = "Error impedit ullam ut aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=584",
                            Name = "Mr. Clark Paucek",
                            Occupancy = 4,
                            Rate = 3.0,
                            SqureFeet = 44,
                            UpdatedDate = new DateTime(2022, 9, 15, 18, 40, 56, 298, DateTimeKind.Local).AddTicks(5279)
                        },
                        new
                        {
                            Id = 35,
                            Amenity = "Magni delectus et id repudiandae nam excepturi et dolore nihil.",
                            CreatedDate = new DateTime(2023, 5, 8, 1, 50, 44, 631, DateTimeKind.Local).AddTicks(1845),
                            Details = "Rerum est sint non.",
                            ImageURL = "https://picsum.photos/640/480/?image=224",
                            Name = "Marilyn Cartwright V",
                            Occupancy = 2,
                            Rate = 3.0,
                            SqureFeet = 556,
                            UpdatedDate = new DateTime(2022, 8, 3, 6, 3, 35, 41, DateTimeKind.Local).AddTicks(2573)
                        },
                        new
                        {
                            Id = 36,
                            Amenity = "Non aut et eius.",
                            CreatedDate = new DateTime(2023, 5, 8, 4, 1, 2, 91, DateTimeKind.Local).AddTicks(6784),
                            Details = "Qui qui exercitationem reiciendis alias sed qui.",
                            ImageURL = "https://picsum.photos/640/480/?image=894",
                            Name = "Ms. Andres Purdy",
                            Occupancy = 6,
                            Rate = 2.0,
                            SqureFeet = 922,
                            UpdatedDate = new DateTime(2022, 9, 20, 16, 35, 11, 92, DateTimeKind.Local).AddTicks(2740)
                        },
                        new
                        {
                            Id = 37,
                            Amenity = "Voluptatem maxime sed itaque.",
                            CreatedDate = new DateTime(2023, 5, 8, 4, 18, 36, 351, DateTimeKind.Local).AddTicks(8274),
                            Details = "Quis modi natus odit dignissimos sunt nemo maiores eos.",
                            ImageURL = "https://picsum.photos/640/480/?image=717",
                            Name = "Forrest Gerhold II",
                            Occupancy = 9,
                            Rate = 5.0,
                            SqureFeet = 416,
                            UpdatedDate = new DateTime(2023, 3, 14, 2, 58, 3, 194, DateTimeKind.Local).AddTicks(365)
                        },
                        new
                        {
                            Id = 38,
                            Amenity = "Qui atque unde vitae.",
                            CreatedDate = new DateTime(2023, 5, 8, 8, 51, 39, 215, DateTimeKind.Local).AddTicks(6097),
                            Details = "Officia veniam sint non.",
                            ImageURL = "https://picsum.photos/640/480/?image=402",
                            Name = "Mrs. Marjorie Greenfelder",
                            Occupancy = 3,
                            Rate = 5.0,
                            SqureFeet = 781,
                            UpdatedDate = new DateTime(2022, 9, 24, 20, 52, 32, 157, DateTimeKind.Local).AddTicks(3248)
                        },
                        new
                        {
                            Id = 39,
                            Amenity = "Totam et saepe enim vitae.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 59, 34, 187, DateTimeKind.Local).AddTicks(155),
                            Details = "Deleniti omnis sapiente inventore.",
                            ImageURL = "https://picsum.photos/640/480/?image=447",
                            Name = "Ms. Jeremy O'Reilly",
                            Occupancy = 10,
                            Rate = 5.0,
                            SqureFeet = 259,
                            UpdatedDate = new DateTime(2023, 1, 10, 0, 54, 11, 824, DateTimeKind.Local).AddTicks(5639)
                        },
                        new
                        {
                            Id = 40,
                            Amenity = "Dolorum cumque illum reprehenderit omnis ea.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 8, 14, 111, DateTimeKind.Local).AddTicks(9261),
                            Details = "Aut laborum sit veritatis.",
                            ImageURL = "https://picsum.photos/640/480/?image=1048",
                            Name = "Casey Marquardt IV",
                            Occupancy = 5,
                            Rate = 5.0,
                            SqureFeet = 704,
                            UpdatedDate = new DateTime(2022, 12, 20, 5, 5, 49, 62, DateTimeKind.Local).AddTicks(5194)
                        },
                        new
                        {
                            Id = 41,
                            Amenity = "Molestiae maiores unde.",
                            CreatedDate = new DateTime(2023, 5, 8, 10, 21, 0, 306, DateTimeKind.Local).AddTicks(7548),
                            Details = "Velit qui nulla velit est alias veritatis molestiae provident doloribus.",
                            ImageURL = "https://picsum.photos/640/480/?image=797",
                            Name = "Mrs. Alexis Raynor",
                            Occupancy = 3,
                            Rate = 4.0,
                            SqureFeet = 609,
                            UpdatedDate = new DateTime(2023, 1, 1, 7, 26, 57, 203, DateTimeKind.Local).AddTicks(5193)
                        },
                        new
                        {
                            Id = 42,
                            Amenity = "Labore repellendus suscipit libero aspernatur atque enim necessitatibus sit eos.",
                            CreatedDate = new DateTime(2023, 5, 7, 23, 55, 23, 585, DateTimeKind.Local).AddTicks(2621),
                            Details = "Voluptate esse quasi magni perspiciatis.",
                            ImageURL = "https://picsum.photos/640/480/?image=864",
                            Name = "Alice Schiller MD",
                            Occupancy = 5,
                            Rate = 2.0,
                            SqureFeet = 619,
                            UpdatedDate = new DateTime(2022, 11, 6, 7, 10, 45, 953, DateTimeKind.Local).AddTicks(5452)
                        },
                        new
                        {
                            Id = 43,
                            Amenity = "Voluptatem repellat ratione necessitatibus ex itaque at.",
                            CreatedDate = new DateTime(2023, 5, 7, 21, 30, 9, 253, DateTimeKind.Local).AddTicks(2424),
                            Details = "Repudiandae architecto officiis qui eius est et dignissimos.",
                            ImageURL = "https://picsum.photos/640/480/?image=863",
                            Name = "Mr. Kristine Schmidt",
                            Occupancy = 7,
                            Rate = 1.0,
                            SqureFeet = 789,
                            UpdatedDate = new DateTime(2022, 8, 28, 10, 16, 36, 26, DateTimeKind.Local).AddTicks(8888)
                        },
                        new
                        {
                            Id = 44,
                            Amenity = "Sit dolore similique est quasi consectetur dicta quisquam sunt qui.",
                            CreatedDate = new DateTime(2023, 5, 8, 16, 28, 25, 644, DateTimeKind.Local).AddTicks(9044),
                            Details = "Non sit nemo vel qui ea aut qui.",
                            ImageURL = "https://picsum.photos/640/480/?image=1043",
                            Name = "Sue Greenholt II",
                            Occupancy = 4,
                            Rate = 4.0,
                            SqureFeet = 554,
                            UpdatedDate = new DateTime(2022, 6, 2, 20, 3, 25, 987, DateTimeKind.Local).AddTicks(489)
                        },
                        new
                        {
                            Id = 45,
                            Amenity = "Quasi quis consequuntur eos quis a quis cum non.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 55, 18, 411, DateTimeKind.Local).AddTicks(6091),
                            Details = "Doloremque dolorem sequi fugiat eum at dicta est quaerat.",
                            ImageURL = "https://picsum.photos/640/480/?image=764",
                            Name = "Ken Thompson PhD",
                            Occupancy = 2,
                            Rate = 3.0,
                            SqureFeet = 255,
                            UpdatedDate = new DateTime(2022, 5, 17, 22, 21, 3, 729, DateTimeKind.Local).AddTicks(1442)
                        },
                        new
                        {
                            Id = 46,
                            Amenity = "Tempora dolorum molestiae ad.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 14, 11, 772, DateTimeKind.Local).AddTicks(7669),
                            Details = "Qui non ut neque et voluptatibus sit ad.",
                            ImageURL = "https://picsum.photos/640/480/?image=966",
                            Name = "Ms. Marguerite McClure",
                            Occupancy = 6,
                            Rate = 4.0,
                            SqureFeet = 175,
                            UpdatedDate = new DateTime(2022, 6, 5, 5, 46, 47, 216, DateTimeKind.Local).AddTicks(1596)
                        },
                        new
                        {
                            Id = 47,
                            Amenity = "Non non dolorem minus consequatur.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 42, 9, 351, DateTimeKind.Local).AddTicks(6551),
                            Details = "Rerum aut et blanditiis quas et libero vel et.",
                            ImageURL = "https://picsum.photos/640/480/?image=665",
                            Name = "Marlon Hoppe MD",
                            Occupancy = 9,
                            Rate = 5.0,
                            SqureFeet = 676,
                            UpdatedDate = new DateTime(2022, 6, 15, 12, 25, 55, 143, DateTimeKind.Local).AddTicks(80)
                        },
                        new
                        {
                            Id = 48,
                            Amenity = "Laudantium sit itaque eligendi cupiditate eius et.",
                            CreatedDate = new DateTime(2023, 5, 8, 2, 42, 54, 729, DateTimeKind.Local).AddTicks(6768),
                            Details = "Facilis aut itaque sunt tenetur.",
                            ImageURL = "https://picsum.photos/640/480/?image=626",
                            Name = "Wilfred Lowe V",
                            Occupancy = 1,
                            Rate = 1.0,
                            SqureFeet = 831,
                            UpdatedDate = new DateTime(2022, 9, 7, 11, 42, 59, 349, DateTimeKind.Local).AddTicks(9516)
                        },
                        new
                        {
                            Id = 49,
                            Amenity = "Ratione harum ea dicta laudantium corrupti.",
                            CreatedDate = new DateTime(2023, 5, 8, 19, 54, 46, 237, DateTimeKind.Local).AddTicks(4539),
                            Details = "Inventore harum suscipit amet ut eos accusantium aut aspernatur nisi.",
                            ImageURL = "https://picsum.photos/640/480/?image=244",
                            Name = "Dr. Alfred Wuckert",
                            Occupancy = 5,
                            Rate = 1.0,
                            SqureFeet = 713,
                            UpdatedDate = new DateTime(2023, 1, 15, 20, 7, 38, 484, DateTimeKind.Local).AddTicks(6074)
                        },
                        new
                        {
                            Id = 50,
                            Amenity = "Quis sit omnis quo voluptatem.",
                            CreatedDate = new DateTime(2023, 5, 7, 22, 13, 35, 948, DateTimeKind.Local).AddTicks(9834),
                            Details = "Qui facilis esse deleniti neque.",
                            ImageURL = "https://picsum.photos/640/480/?image=324",
                            Name = "Miss George Bartell",
                            Occupancy = 4,
                            Rate = 3.0,
                            SqureFeet = 739,
                            UpdatedDate = new DateTime(2022, 10, 21, 15, 41, 51, 428, DateTimeKind.Local).AddTicks(2357)
                        },
                        new
                        {
                            Id = 51,
                            Amenity = "Iure accusantium dolor quo expedita et sed pariatur sed voluptatibus.",
                            CreatedDate = new DateTime(2023, 5, 8, 9, 29, 47, 484, DateTimeKind.Local).AddTicks(7688),
                            Details = "Voluptate ea aut harum non deleniti et aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=518",
                            Name = "Jamie Baumbach II",
                            Occupancy = 9,
                            Rate = 5.0,
                            SqureFeet = 708,
                            UpdatedDate = new DateTime(2022, 12, 10, 22, 52, 51, 614, DateTimeKind.Local).AddTicks(1727)
                        },
                        new
                        {
                            Id = 52,
                            Amenity = "In id harum temporibus qui perspiciatis facilis accusamus.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 34, 21, 390, DateTimeKind.Local).AddTicks(986),
                            Details = "Saepe nihil maxime ut aut sint aliquam sit sit vitae.",
                            ImageURL = "https://picsum.photos/640/480/?image=1056",
                            Name = "Mrs. Marcia Block",
                            Occupancy = 7,
                            Rate = 4.0,
                            SqureFeet = 514,
                            UpdatedDate = new DateTime(2023, 4, 20, 23, 43, 51, 736, DateTimeKind.Local).AddTicks(6096)
                        },
                        new
                        {
                            Id = 53,
                            Amenity = "Quidem dolor maiores delectus tenetur aperiam.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 16, 48, 373, DateTimeKind.Local).AddTicks(5446),
                            Details = "Aliquam sapiente sit qui quo.",
                            ImageURL = "https://picsum.photos/640/480/?image=1064",
                            Name = "Eric Osinski DDS",
                            Occupancy = 6,
                            Rate = 3.0,
                            SqureFeet = 442,
                            UpdatedDate = new DateTime(2022, 9, 3, 23, 47, 19, 603, DateTimeKind.Local).AddTicks(4522)
                        },
                        new
                        {
                            Id = 54,
                            Amenity = "Ad id nulla.",
                            CreatedDate = new DateTime(2023, 5, 7, 20, 33, 28, 436, DateTimeKind.Local).AddTicks(7072),
                            Details = "Quia neque velit.",
                            ImageURL = "https://picsum.photos/640/480/?image=1080",
                            Name = "Sherman Morar IV",
                            Occupancy = 4,
                            Rate = 3.0,
                            SqureFeet = 5,
                            UpdatedDate = new DateTime(2022, 12, 5, 1, 53, 27, 69, DateTimeKind.Local).AddTicks(2557)
                        },
                        new
                        {
                            Id = 55,
                            Amenity = "Earum ut qui quia omnis et vitae est est.",
                            CreatedDate = new DateTime(2023, 5, 8, 13, 22, 54, 918, DateTimeKind.Local).AddTicks(5371),
                            Details = "Voluptatem explicabo amet illum fuga quis ea placeat ratione perferendis.",
                            ImageURL = "https://picsum.photos/640/480/?image=443",
                            Name = "Camille Conroy Sr.",
                            Occupancy = 7,
                            Rate = 1.0,
                            SqureFeet = 443,
                            UpdatedDate = new DateTime(2023, 2, 16, 3, 40, 9, 226, DateTimeKind.Local).AddTicks(6198)
                        },
                        new
                        {
                            Id = 56,
                            Amenity = "Qui quas ullam tenetur odio at.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 51, 44, 0, DateTimeKind.Local).AddTicks(15),
                            Details = "Consequuntur et odio velit praesentium quas at esse enim eius.",
                            ImageURL = "https://picsum.photos/640/480/?image=461",
                            Name = "Jaime Koss I",
                            Occupancy = 9,
                            Rate = 2.0,
                            SqureFeet = 207,
                            UpdatedDate = new DateTime(2022, 8, 25, 18, 1, 59, 176, DateTimeKind.Local).AddTicks(3241)
                        },
                        new
                        {
                            Id = 57,
                            Amenity = "Consequatur laudantium ad nam ducimus sed ut voluptates sed.",
                            CreatedDate = new DateTime(2023, 5, 8, 14, 39, 58, 602, DateTimeKind.Local).AddTicks(3809),
                            Details = "Officiis eum quo.",
                            ImageURL = "https://picsum.photos/640/480/?image=437",
                            Name = "Jason Lynch Jr.",
                            Occupancy = 3,
                            Rate = 2.0,
                            SqureFeet = 335,
                            UpdatedDate = new DateTime(2022, 12, 5, 6, 10, 7, 179, DateTimeKind.Local).AddTicks(5095)
                        },
                        new
                        {
                            Id = 58,
                            Amenity = "In ipsam voluptatibus.",
                            CreatedDate = new DateTime(2023, 5, 8, 8, 17, 54, 814, DateTimeKind.Local).AddTicks(3597),
                            Details = "Molestias provident numquam omnis deserunt ipsum voluptas ut blanditiis quia.",
                            ImageURL = "https://picsum.photos/640/480/?image=650",
                            Name = "Caroline Bartoletti V",
                            Occupancy = 6,
                            Rate = 4.0,
                            SqureFeet = 728,
                            UpdatedDate = new DateTime(2022, 8, 17, 1, 4, 53, 110, DateTimeKind.Local).AddTicks(1330)
                        },
                        new
                        {
                            Id = 59,
                            Amenity = "Sit beatae aut sapiente libero qui quis.",
                            CreatedDate = new DateTime(2023, 5, 8, 10, 53, 13, 440, DateTimeKind.Local).AddTicks(9450),
                            Details = "Labore rerum debitis nobis numquam.",
                            ImageURL = "https://picsum.photos/640/480/?image=163",
                            Name = "Ms. Viola Schinner",
                            Occupancy = 4,
                            Rate = 3.0,
                            SqureFeet = 818,
                            UpdatedDate = new DateTime(2023, 2, 15, 12, 31, 51, 224, DateTimeKind.Local).AddTicks(6284)
                        },
                        new
                        {
                            Id = 60,
                            Amenity = "Vitae distinctio blanditiis quo modi temporibus ut tempore quia vitae.",
                            CreatedDate = new DateTime(2023, 5, 8, 17, 12, 1, 387, DateTimeKind.Local).AddTicks(2879),
                            Details = "Alias laudantium rerum necessitatibus et.",
                            ImageURL = "https://picsum.photos/640/480/?image=812",
                            Name = "Ms. Pat Fay",
                            Occupancy = 7,
                            Rate = 3.0,
                            SqureFeet = 721,
                            UpdatedDate = new DateTime(2023, 3, 24, 22, 43, 16, 154, DateTimeKind.Local).AddTicks(6886)
                        },
                        new
                        {
                            Id = 61,
                            Amenity = "Rerum reprehenderit fugiat labore sed quisquam dolorem atque maiores soluta.",
                            CreatedDate = new DateTime(2023, 5, 8, 13, 39, 46, 899, DateTimeKind.Local).AddTicks(7799),
                            Details = "Et porro voluptatum recusandae.",
                            ImageURL = "https://picsum.photos/640/480/?image=701",
                            Name = "Mrs. Gustavo Schaden",
                            Occupancy = 5,
                            Rate = 1.0,
                            SqureFeet = 801,
                            UpdatedDate = new DateTime(2023, 2, 15, 23, 47, 40, 804, DateTimeKind.Local).AddTicks(4569)
                        },
                        new
                        {
                            Id = 62,
                            Amenity = "Tenetur magnam iste.",
                            CreatedDate = new DateTime(2023, 5, 8, 15, 15, 1, 664, DateTimeKind.Local).AddTicks(9078),
                            Details = "Sit soluta saepe voluptas vero.",
                            ImageURL = "https://picsum.photos/640/480/?image=777",
                            Name = "Mr. Bernadette MacGyver",
                            Occupancy = 6,
                            Rate = 5.0,
                            SqureFeet = 34,
                            UpdatedDate = new DateTime(2023, 4, 10, 5, 8, 30, 580, DateTimeKind.Local).AddTicks(1070)
                        },
                        new
                        {
                            Id = 63,
                            Amenity = "Sed sint culpa et sit adipisci.",
                            CreatedDate = new DateTime(2023, 5, 8, 17, 30, 49, 283, DateTimeKind.Local).AddTicks(2474),
                            Details = "Qui culpa et vero totam.",
                            ImageURL = "https://picsum.photos/640/480/?image=155",
                            Name = "Mrs. Clint Pfannerstill",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 680,
                            UpdatedDate = new DateTime(2023, 3, 5, 5, 59, 50, 668, DateTimeKind.Local).AddTicks(8921)
                        },
                        new
                        {
                            Id = 64,
                            Amenity = "Aut tenetur odio et voluptas quam doloribus.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 28, 20, 807, DateTimeKind.Local).AddTicks(141),
                            Details = "Consequuntur similique inventore voluptate molestiae.",
                            ImageURL = "https://picsum.photos/640/480/?image=385",
                            Name = "Jenna Kerluke PhD",
                            Occupancy = 3,
                            Rate = 4.0,
                            SqureFeet = 968,
                            UpdatedDate = new DateTime(2023, 1, 27, 2, 43, 48, 806, DateTimeKind.Local).AddTicks(2743)
                        },
                        new
                        {
                            Id = 65,
                            Amenity = "Expedita sunt ut culpa voluptas tenetur rerum occaecati.",
                            CreatedDate = new DateTime(2023, 5, 8, 17, 46, 21, 991, DateTimeKind.Local).AddTicks(162),
                            Details = "Ab non quidem non omnis.",
                            ImageURL = "https://picsum.photos/640/480/?image=156",
                            Name = "Mr. Philip Greenfelder",
                            Occupancy = 8,
                            Rate = 5.0,
                            SqureFeet = 482,
                            UpdatedDate = new DateTime(2022, 9, 14, 18, 55, 28, 724, DateTimeKind.Local).AddTicks(7109)
                        },
                        new
                        {
                            Id = 66,
                            Amenity = "Ullam ea et ex quas aut minus.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 50, 53, 686, DateTimeKind.Local).AddTicks(3458),
                            Details = "Praesentium dolorem corporis dolor.",
                            ImageURL = "https://picsum.photos/640/480/?image=530",
                            Name = "Ms. Jennie Ward",
                            Occupancy = 3,
                            Rate = 4.0,
                            SqureFeet = 729,
                            UpdatedDate = new DateTime(2022, 12, 4, 21, 1, 44, 488, DateTimeKind.Local).AddTicks(1083)
                        },
                        new
                        {
                            Id = 67,
                            Amenity = "Esse saepe occaecati expedita.",
                            CreatedDate = new DateTime(2023, 5, 7, 23, 40, 18, 844, DateTimeKind.Local).AddTicks(9925),
                            Details = "At qui debitis quidem ut porro recusandae voluptate quia quaerat.",
                            ImageURL = "https://picsum.photos/640/480/?image=310",
                            Name = "Leslie Jacobs Jr.",
                            Occupancy = 5,
                            Rate = 4.0,
                            SqureFeet = 507,
                            UpdatedDate = new DateTime(2022, 9, 22, 4, 8, 57, 797, DateTimeKind.Local).AddTicks(867)
                        },
                        new
                        {
                            Id = 68,
                            Amenity = "Quod excepturi et sed fuga odit.",
                            CreatedDate = new DateTime(2023, 5, 7, 22, 54, 26, 1, DateTimeKind.Local).AddTicks(1620),
                            Details = "Illum autem autem iure quaerat vero molestiae laboriosam.",
                            ImageURL = "https://picsum.photos/640/480/?image=71",
                            Name = "Miss Vicki Carroll",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 763,
                            UpdatedDate = new DateTime(2022, 5, 29, 22, 49, 37, 691, DateTimeKind.Local).AddTicks(5514)
                        },
                        new
                        {
                            Id = 69,
                            Amenity = "Iste ut quis asperiores ratione saepe voluptatibus.",
                            CreatedDate = new DateTime(2023, 5, 8, 5, 32, 13, 177, DateTimeKind.Local).AddTicks(4038),
                            Details = "Vel in officiis sed.",
                            ImageURL = "https://picsum.photos/640/480/?image=608",
                            Name = "Miss Ramona Brakus",
                            Occupancy = 1,
                            Rate = 2.0,
                            SqureFeet = 984,
                            UpdatedDate = new DateTime(2023, 1, 27, 8, 2, 24, 195, DateTimeKind.Local).AddTicks(9971)
                        },
                        new
                        {
                            Id = 70,
                            Amenity = "Hic enim culpa quo.",
                            CreatedDate = new DateTime(2023, 5, 7, 20, 38, 0, 375, DateTimeKind.Local).AddTicks(9902),
                            Details = "Est ab sunt sint.",
                            ImageURL = "https://picsum.photos/640/480/?image=527",
                            Name = "Lynette Heidenreich DDS",
                            Occupancy = 7,
                            Rate = 3.0,
                            SqureFeet = 166,
                            UpdatedDate = new DateTime(2022, 11, 26, 0, 43, 55, 23, DateTimeKind.Local).AddTicks(9641)
                        },
                        new
                        {
                            Id = 71,
                            Amenity = "Laudantium enim qui qui.",
                            CreatedDate = new DateTime(2023, 5, 8, 12, 54, 38, 512, DateTimeKind.Local).AddTicks(7293),
                            Details = "Autem ipsa dolorum repudiandae eos.",
                            ImageURL = "https://picsum.photos/640/480/?image=907",
                            Name = "Dr. Sheryl King",
                            Occupancy = 5,
                            Rate = 3.0,
                            SqureFeet = 421,
                            UpdatedDate = new DateTime(2022, 11, 28, 0, 21, 22, 92, DateTimeKind.Local).AddTicks(8211)
                        },
                        new
                        {
                            Id = 72,
                            Amenity = "Qui ipsa et architecto dolore consectetur aut sed doloribus.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 42, 25, 531, DateTimeKind.Local).AddTicks(4325),
                            Details = "Ducimus occaecati placeat perspiciatis assumenda est explicabo est.",
                            ImageURL = "https://picsum.photos/640/480/?image=238",
                            Name = "Brandi Bartell DVM",
                            Occupancy = 3,
                            Rate = 1.0,
                            SqureFeet = 321,
                            UpdatedDate = new DateTime(2023, 4, 28, 1, 42, 24, 701, DateTimeKind.Local).AddTicks(3028)
                        },
                        new
                        {
                            Id = 73,
                            Amenity = "Et est ipsum sit corrupti tempore nulla animi sunt tempore.",
                            CreatedDate = new DateTime(2023, 5, 8, 7, 35, 15, 96, DateTimeKind.Local).AddTicks(2042),
                            Details = "Aut non nulla quam et sint quis est cumque et.",
                            ImageURL = "https://picsum.photos/640/480/?image=520",
                            Name = "Eugene Howell DDS",
                            Occupancy = 9,
                            Rate = 5.0,
                            SqureFeet = 11,
                            UpdatedDate = new DateTime(2023, 1, 15, 9, 22, 47, 485, DateTimeKind.Local).AddTicks(8162)
                        },
                        new
                        {
                            Id = 74,
                            Amenity = "Ullam porro est.",
                            CreatedDate = new DateTime(2023, 5, 8, 2, 53, 51, 865, DateTimeKind.Local).AddTicks(7874),
                            Details = "In minus repellat ut sequi quia et.",
                            ImageURL = "https://picsum.photos/640/480/?image=771",
                            Name = "Miss Tonya Toy",
                            Occupancy = 1,
                            Rate = 4.0,
                            SqureFeet = 575,
                            UpdatedDate = new DateTime(2022, 10, 3, 10, 22, 12, 685, DateTimeKind.Local).AddTicks(60)
                        },
                        new
                        {
                            Id = 75,
                            Amenity = "Consequatur recusandae et numquam corporis voluptas architecto corrupti eveniet eligendi.",
                            CreatedDate = new DateTime(2023, 5, 8, 18, 22, 46, 113, DateTimeKind.Local).AddTicks(9886),
                            Details = "Non soluta placeat dignissimos iste maxime voluptas voluptatem.",
                            ImageURL = "https://picsum.photos/640/480/?image=355",
                            Name = "Ms. Luz Reinger",
                            Occupancy = 3,
                            Rate = 3.0,
                            SqureFeet = 520,
                            UpdatedDate = new DateTime(2023, 2, 11, 17, 1, 57, 208, DateTimeKind.Local).AddTicks(7210)
                        },
                        new
                        {
                            Id = 76,
                            Amenity = "Similique placeat neque vero consequatur non ut dolorem ut.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 33, 7, 918, DateTimeKind.Local).AddTicks(7846),
                            Details = "Occaecati officiis sunt iure illo possimus quia ratione.",
                            ImageURL = "https://picsum.photos/640/480/?image=434",
                            Name = "Mr. Billie Strosin",
                            Occupancy = 10,
                            Rate = 4.0,
                            SqureFeet = 822,
                            UpdatedDate = new DateTime(2022, 8, 10, 11, 5, 3, 345, DateTimeKind.Local).AddTicks(3014)
                        },
                        new
                        {
                            Id = 77,
                            Amenity = "Omnis iste architecto qui.",
                            CreatedDate = new DateTime(2023, 5, 8, 0, 12, 58, 696, DateTimeKind.Local).AddTicks(7427),
                            Details = "Repellendus at voluptate.",
                            ImageURL = "https://picsum.photos/640/480/?image=991",
                            Name = "Heather Padberg I",
                            Occupancy = 6,
                            Rate = 1.0,
                            SqureFeet = 806,
                            UpdatedDate = new DateTime(2022, 12, 26, 18, 51, 13, 6, DateTimeKind.Local).AddTicks(4837)
                        },
                        new
                        {
                            Id = 78,
                            Amenity = "Sit facilis ut dolor vitae perferendis.",
                            CreatedDate = new DateTime(2023, 5, 8, 12, 56, 9, 50, DateTimeKind.Local).AddTicks(5557),
                            Details = "Voluptatem impedit animi eum hic qui reiciendis.",
                            ImageURL = "https://picsum.photos/640/480/?image=65",
                            Name = "Miss Darren Toy",
                            Occupancy = 6,
                            Rate = 5.0,
                            SqureFeet = 419,
                            UpdatedDate = new DateTime(2022, 9, 22, 1, 15, 18, 735, DateTimeKind.Local).AddTicks(8939)
                        },
                        new
                        {
                            Id = 79,
                            Amenity = "Quia omnis aspernatur aut.",
                            CreatedDate = new DateTime(2023, 5, 8, 6, 48, 8, 544, DateTimeKind.Local).AddTicks(4517),
                            Details = "Eum soluta itaque ut minus fugiat repellat.",
                            ImageURL = "https://picsum.photos/640/480/?image=839",
                            Name = "Mrs. Robin Smith",
                            Occupancy = 10,
                            Rate = 5.0,
                            SqureFeet = 393,
                            UpdatedDate = new DateTime(2022, 11, 7, 6, 26, 29, 363, DateTimeKind.Local).AddTicks(9073)
                        },
                        new
                        {
                            Id = 80,
                            Amenity = "Officia quia illum omnis quia culpa odit laborum cumque.",
                            CreatedDate = new DateTime(2023, 5, 7, 22, 35, 51, 256, DateTimeKind.Local).AddTicks(1674),
                            Details = "Numquam neque perspiciatis.",
                            ImageURL = "https://picsum.photos/640/480/?image=102",
                            Name = "Brent Mann DVM",
                            Occupancy = 1,
                            Rate = 1.0,
                            SqureFeet = 666,
                            UpdatedDate = new DateTime(2023, 2, 12, 16, 32, 18, 962, DateTimeKind.Local).AddTicks(6446)
                        },
                        new
                        {
                            Id = 81,
                            Amenity = "Quis necessitatibus labore.",
                            CreatedDate = new DateTime(2023, 5, 8, 6, 44, 13, 160, DateTimeKind.Local).AddTicks(1888),
                            Details = "Et eos eveniet voluptate.",
                            ImageURL = "https://picsum.photos/640/480/?image=19",
                            Name = "Mr. Aubrey Kohler",
                            Occupancy = 5,
                            Rate = 3.0,
                            SqureFeet = 432,
                            UpdatedDate = new DateTime(2022, 7, 11, 17, 52, 34, 520, DateTimeKind.Local).AddTicks(5446)
                        },
                        new
                        {
                            Id = 82,
                            Amenity = "Et quia similique atque incidunt.",
                            CreatedDate = new DateTime(2023, 5, 8, 12, 10, 40, 806, DateTimeKind.Local).AddTicks(7881),
                            Details = "Reiciendis ut atque sint quod nemo voluptatem aliquid veniam.",
                            ImageURL = "https://picsum.photos/640/480/?image=41",
                            Name = "Jean Doyle I",
                            Occupancy = 5,
                            Rate = 4.0,
                            SqureFeet = 313,
                            UpdatedDate = new DateTime(2022, 9, 26, 6, 33, 16, 595, DateTimeKind.Local).AddTicks(4700)
                        },
                        new
                        {
                            Id = 83,
                            Amenity = "Qui repellat odit et.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 30, 18, 194, DateTimeKind.Local).AddTicks(6338),
                            Details = "Quam architecto rerum fugiat et itaque pariatur ea.",
                            ImageURL = "https://picsum.photos/640/480/?image=179",
                            Name = "Miss Merle Boehm",
                            Occupancy = 8,
                            Rate = 1.0,
                            SqureFeet = 157,
                            UpdatedDate = new DateTime(2023, 2, 18, 19, 2, 53, 988, DateTimeKind.Local).AddTicks(2251)
                        },
                        new
                        {
                            Id = 84,
                            Amenity = "Aliquid doloribus cupiditate aut et ipsam.",
                            CreatedDate = new DateTime(2023, 5, 7, 20, 11, 14, 886, DateTimeKind.Local).AddTicks(5089),
                            Details = "Quas architecto cumque quis corporis dolores quod non unde doloribus.",
                            ImageURL = "https://picsum.photos/640/480/?image=114",
                            Name = "Dr. Elsie Vandervort",
                            Occupancy = 10,
                            Rate = 3.0,
                            SqureFeet = 966,
                            UpdatedDate = new DateTime(2023, 1, 6, 9, 58, 32, 1, DateTimeKind.Local).AddTicks(8226)
                        },
                        new
                        {
                            Id = 85,
                            Amenity = "Nihil sed maiores earum eligendi labore consequuntur.",
                            CreatedDate = new DateTime(2023, 5, 8, 17, 6, 10, 851, DateTimeKind.Local).AddTicks(3121),
                            Details = "Cum vel id commodi ut.",
                            ImageURL = "https://picsum.photos/640/480/?image=914",
                            Name = "Alfred Runolfsdottir PhD",
                            Occupancy = 6,
                            Rate = 3.0,
                            SqureFeet = 622,
                            UpdatedDate = new DateTime(2022, 6, 5, 1, 56, 32, 444, DateTimeKind.Local).AddTicks(1886)
                        },
                        new
                        {
                            Id = 86,
                            Amenity = "Aspernatur odit atque voluptatum ut officia dolorem officiis.",
                            CreatedDate = new DateTime(2023, 5, 8, 14, 35, 28, 488, DateTimeKind.Local).AddTicks(767),
                            Details = "Voluptatem dolorem mollitia aut ratione porro quae unde sit.",
                            ImageURL = "https://picsum.photos/640/480/?image=1013",
                            Name = "Lawrence Smith IV",
                            Occupancy = 10,
                            Rate = 1.0,
                            SqureFeet = 385,
                            UpdatedDate = new DateTime(2022, 12, 7, 11, 14, 24, 883, DateTimeKind.Local).AddTicks(6643)
                        },
                        new
                        {
                            Id = 87,
                            Amenity = "Rerum adipisci a et eaque nihil vel ipsa ea.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 40, 48, 69, DateTimeKind.Local).AddTicks(9519),
                            Details = "Quia dolorem blanditiis error et maxime veniam optio.",
                            ImageURL = "https://picsum.photos/640/480/?image=575",
                            Name = "Mrs. Jesse Huel",
                            Occupancy = 1,
                            Rate = 2.0,
                            SqureFeet = 290,
                            UpdatedDate = new DateTime(2022, 10, 10, 8, 28, 52, 498, DateTimeKind.Local).AddTicks(767)
                        },
                        new
                        {
                            Id = 88,
                            Amenity = "Ut est saepe odit nulla ut id repudiandae.",
                            CreatedDate = new DateTime(2023, 5, 8, 16, 16, 44, 50, DateTimeKind.Local).AddTicks(9579),
                            Details = "Et et impedit aut dolores voluptatibus quod quis velit ut.",
                            ImageURL = "https://picsum.photos/640/480/?image=105",
                            Name = "Miss Noel Goyette",
                            Occupancy = 2,
                            Rate = 5.0,
                            SqureFeet = 22,
                            UpdatedDate = new DateTime(2022, 6, 24, 15, 24, 1, 681, DateTimeKind.Local).AddTicks(2231)
                        },
                        new
                        {
                            Id = 89,
                            Amenity = "Quis vel voluptates consequatur incidunt molestiae ipsam iste inventore.",
                            CreatedDate = new DateTime(2023, 5, 8, 15, 41, 2, 71, DateTimeKind.Local).AddTicks(5842),
                            Details = "Aut doloribus rerum enim aperiam.",
                            ImageURL = "https://picsum.photos/640/480/?image=742",
                            Name = "Mrs. Trevor Langworth",
                            Occupancy = 7,
                            Rate = 2.0,
                            SqureFeet = 838,
                            UpdatedDate = new DateTime(2022, 10, 9, 18, 26, 39, 347, DateTimeKind.Local).AddTicks(740)
                        },
                        new
                        {
                            Id = 90,
                            Amenity = "Quasi voluptas reprehenderit.",
                            CreatedDate = new DateTime(2023, 5, 8, 10, 38, 47, 512, DateTimeKind.Local).AddTicks(6263),
                            Details = "Voluptatem impedit quam ad.",
                            ImageURL = "https://picsum.photos/640/480/?image=286",
                            Name = "Krystal Grimes Sr.",
                            Occupancy = 3,
                            Rate = 2.0,
                            SqureFeet = 575,
                            UpdatedDate = new DateTime(2023, 4, 16, 9, 51, 0, 836, DateTimeKind.Local).AddTicks(3393)
                        },
                        new
                        {
                            Id = 91,
                            Amenity = "Repellendus at exercitationem dolore.",
                            CreatedDate = new DateTime(2023, 5, 8, 14, 45, 23, 555, DateTimeKind.Local).AddTicks(9148),
                            Details = "Occaecati molestias nihil qui.",
                            ImageURL = "https://picsum.photos/640/480/?image=85",
                            Name = "Bridget Koepp Jr.",
                            Occupancy = 6,
                            Rate = 2.0,
                            SqureFeet = 77,
                            UpdatedDate = new DateTime(2023, 1, 28, 1, 42, 37, 312, DateTimeKind.Local).AddTicks(84)
                        },
                        new
                        {
                            Id = 92,
                            Amenity = "Repellendus iure numquam blanditiis atque.",
                            CreatedDate = new DateTime(2023, 5, 8, 2, 35, 13, 121, DateTimeKind.Local).AddTicks(351),
                            Details = "Voluptatum impedit assumenda corporis.",
                            ImageURL = "https://picsum.photos/640/480/?image=538",
                            Name = "Dr. Willie Von",
                            Occupancy = 3,
                            Rate = 5.0,
                            SqureFeet = 915,
                            UpdatedDate = new DateTime(2022, 8, 23, 19, 41, 2, 461, DateTimeKind.Local).AddTicks(5132)
                        },
                        new
                        {
                            Id = 93,
                            Amenity = "Quis beatae illum est rerum quas cumque aut mollitia.",
                            CreatedDate = new DateTime(2023, 5, 8, 1, 14, 44, 910, DateTimeKind.Local).AddTicks(106),
                            Details = "Velit quos est pariatur ipsa tempore aut.",
                            ImageURL = "https://picsum.photos/640/480/?image=514",
                            Name = "Mr. Beatrice Barrows",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 789,
                            UpdatedDate = new DateTime(2023, 4, 12, 17, 21, 29, 1, DateTimeKind.Local).AddTicks(8594)
                        },
                        new
                        {
                            Id = 94,
                            Amenity = "Sapiente pariatur atque tempora animi.",
                            CreatedDate = new DateTime(2023, 5, 8, 2, 29, 54, 806, DateTimeKind.Local).AddTicks(6541),
                            Details = "Praesentium optio nostrum nulla sunt dolor consequatur.",
                            ImageURL = "https://picsum.photos/640/480/?image=707",
                            Name = "Mr. Latoya Blick",
                            Occupancy = 7,
                            Rate = 5.0,
                            SqureFeet = 224,
                            UpdatedDate = new DateTime(2022, 9, 22, 17, 43, 58, 707, DateTimeKind.Local).AddTicks(2338)
                        },
                        new
                        {
                            Id = 95,
                            Amenity = "Sit dolores assumenda consectetur eos in rerum porro dignissimos laborum.",
                            CreatedDate = new DateTime(2023, 5, 8, 4, 46, 47, 121, DateTimeKind.Local).AddTicks(9862),
                            Details = "Est iure optio nobis voluptatem aut cum.",
                            ImageURL = "https://picsum.photos/640/480/?image=238",
                            Name = "Kate Moore V",
                            Occupancy = 4,
                            Rate = 5.0,
                            SqureFeet = 281,
                            UpdatedDate = new DateTime(2022, 9, 16, 23, 53, 2, 362, DateTimeKind.Local).AddTicks(9819)
                        },
                        new
                        {
                            Id = 96,
                            Amenity = "Quo numquam repellendus tempora dolorum consequatur culpa laboriosam.",
                            CreatedDate = new DateTime(2023, 5, 8, 10, 39, 25, 361, DateTimeKind.Local).AddTicks(3333),
                            Details = "Aut autem maiores exercitationem ad cumque.",
                            ImageURL = "https://picsum.photos/640/480/?image=460",
                            Name = "Dr. Eunice Crooks",
                            Occupancy = 4,
                            Rate = 2.0,
                            SqureFeet = 136,
                            UpdatedDate = new DateTime(2022, 12, 19, 21, 32, 18, 584, DateTimeKind.Local).AddTicks(8301)
                        },
                        new
                        {
                            Id = 97,
                            Amenity = "Fugiat eligendi vero.",
                            CreatedDate = new DateTime(2023, 5, 7, 20, 9, 5, 895, DateTimeKind.Local).AddTicks(5376),
                            Details = "Libero tempore repudiandae enim molestias ex nesciunt ducimus.",
                            ImageURL = "https://picsum.photos/640/480/?image=348",
                            Name = "Dwayne Lemke I",
                            Occupancy = 1,
                            Rate = 5.0,
                            SqureFeet = 384,
                            UpdatedDate = new DateTime(2022, 8, 24, 3, 0, 0, 872, DateTimeKind.Local).AddTicks(6101)
                        },
                        new
                        {
                            Id = 98,
                            Amenity = "Voluptas fugiat velit suscipit vero doloremque asperiores et ut vitae.",
                            CreatedDate = new DateTime(2023, 5, 8, 11, 26, 52, 261, DateTimeKind.Local).AddTicks(5946),
                            Details = "Eveniet exercitationem dolor nostrum et.",
                            ImageURL = "https://picsum.photos/640/480/?image=1006",
                            Name = "Mr. Willie McKenzie",
                            Occupancy = 6,
                            Rate = 5.0,
                            SqureFeet = 135,
                            UpdatedDate = new DateTime(2022, 11, 14, 19, 31, 30, 75, DateTimeKind.Local).AddTicks(3540)
                        },
                        new
                        {
                            Id = 99,
                            Amenity = "Molestiae numquam nulla voluptatem fugiat unde ea dolor voluptatum sed.",
                            CreatedDate = new DateTime(2023, 5, 8, 17, 25, 8, 124, DateTimeKind.Local).AddTicks(7041),
                            Details = "Inventore delectus nobis consequuntur.",
                            ImageURL = "https://picsum.photos/640/480/?image=833",
                            Name = "Mr. Darin Johns",
                            Occupancy = 8,
                            Rate = 2.0,
                            SqureFeet = 656,
                            UpdatedDate = new DateTime(2023, 4, 19, 9, 47, 44, 580, DateTimeKind.Local).AddTicks(2751)
                        },
                        new
                        {
                            Id = 100,
                            Amenity = "Exercitationem qui nobis possimus.",
                            CreatedDate = new DateTime(2023, 5, 8, 15, 48, 47, 466, DateTimeKind.Local).AddTicks(9539),
                            Details = "Amet excepturi sint tenetur deleniti officiis ut eum consequatur in.",
                            ImageURL = "https://picsum.photos/640/480/?image=922",
                            Name = "Jesse Shields II",
                            Occupancy = 9,
                            Rate = 3.0,
                            SqureFeet = 862,
                            UpdatedDate = new DateTime(2022, 5, 30, 11, 59, 34, 279, DateTimeKind.Local).AddTicks(545)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
